
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 99
#define YY_END_OF_BUFFER 100
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[294] =
    {   0,
        0,    0,   81,   81,    0,    0,  100,   99,   52,   43,
       59,   78,   28,   99,   53,   54,   26,   24,   48,   25,
       47,   27,   82,   82,   49,   51,   33,   40,   32,   46,
       99,   98,   57,   58,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       55,   99,   56,   40,   81,   81,   61,   77,   62,   99,
       62,   31,   78,   41,   29,   44,   93,    0,    0,   86,
        0,    0,    0,    0,    0,    0,    0,   82,   82,   94,
       83,   50,   35,   30,   34,    0,   96,   98,    0,   95,
       95,   95,   95,   95,   95,    6,   95,   95,   95,   95,

       95,    7,   13,   95,   95,   16,   95,   95,   95,   95,
       95,   95,   95,   42,    0,   81,   81,   61,   60,   73,
       74,   72,   64,   65,   70,   68,   63,   69,   71,   66,
       67,   76,   45,   93,   93,   93,   92,   86,   87,   90,
        0,   84,    0,    0,   92,    0,   88,    0,   87,    0,
        0,    0,    0,    0,   92,   94,    0,    0,   83,   94,
       94,   92,    0,   82,   83,   36,   37,   97,   96,    0,
        1,   95,   95,    4,   95,   10,   95,   95,   95,   12,
       14,   15,   95,   95,   95,   95,   95,   95,   95,    0,
       81,   74,   76,   75,    0,   93,    0,   86,   87,   90,

       91,   91,   84,   85,   85,   92,    0,   88,   89,   89,
       87,    0,    0,    0,   92,   92,   93,   94,   93,   92,
       83,   94,   92,   92,   94,   83,   97,    0,   95,   95,
       95,    8,   95,   38,   95,   95,   95,   18,   95,   20,
       21,   95,   95,    0,   80,   74,   75,    0,   93,   92,
       90,   91,   91,   84,   85,   85,   92,   88,   89,   89,
        0,   92,   93,   94,   94,   93,   93,    0,   92,   92,
        2,    3,   95,    9,   95,   11,   95,   19,   22,   23,
        0,    0,   93,   93,   92,   95,   39,   17,   79,   93,
       95,    5,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   27,   29,   30,   27,
       31,   31,   31,   31,   31,   31,   31,   31,   32,   31,
       31,   31,   31,   31,   31,   31,   31,   33,   31,   31,
       34,   35,   36,    1,   37,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   47,   47,   48,   47,   49,
       50,   51,   52,   53,   54,   55,   56,   57,   58,   59,
       47,   47,   60,   61,   62,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[63] =
    {   0,
        1,    2,    1,    3,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    1,    6,    6,    6,    6,    1,
        1,    1,    1,    1,    1,    7,    6,    6,    6,    6,
        8,    8,    8,    1,    4,    1,    9,   10,   10,   10,
       10,   10,   10,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,    4,
        1,    4
    } ;

static const flex_int16_t yy_base[312] =
    {   0,
        0,  708,  726,   61,   62,   66,  727, 1228, 1228,  703,
     1228,    0, 1228,  718, 1228, 1228,  712, 1228, 1228, 1228,
       58, 1228,  115,   69,  695, 1228,  691,  685,  677, 1228,
      673,    0, 1228, 1228,   55,   51,   65,   64,   66,   88,
       67,  684,   76,   68,   77,   79,   99,   82,   89,   59,
     1228,  628, 1228,   71,    0,  646,    0, 1228,  625,  171,
     1228, 1228,    0, 1228, 1228,  669,  144,  153,  160,  166,
      175,  149,  182,  180,  644,  215,  220,  250,  259,  291,
      281, 1228,  656,  646, 1228,    0,    0,    0,  298,  644,
      109,  101,   95,  135,  137,  643,  150,  180,  171,  193,

      106,  641,  640,  194,  191,  639,  204,  197,  202,  209,
      215,  208,  226, 1228,  609,    0,  601,    0, 1228, 1228,
      265, 1228, 1228, 1228, 1228, 1228, 1228, 1228, 1228, 1228,
     1228,  320,  630,  308,  337,  350,  354,  360,  363,  269,
      303,  376,  371,  312,  385,  389,  606,  592,  393,  382,
      397,  407,  591,  419,  429,  446,  456,  473,  483,  490,
      500,  512,  522,  539,  549, 1228, 1228,    0,    0,  599,
      598,  244,  201,  247,  436,  593,  235,  256,  289,  582,
      569,  566,  327,  270,  343,  368,  398,  372,  406,  531,
      519,  411,  576,    0,  571,  583,  505,  593,  605,  415,

      468,  495,  608,  615,  619,  630,  527,  497,  443,  431,
      623,  645,  654,  660,  687,  693,  702,  724,  732,  741,
      763,  771,  780,  802,  810,  819,    0,  444,  428,  425,
      521,  437,  332, 1228,  407,  427,  443,  351,  480,  338,
      330,  534,  439,  296,    0, 1228, 1228,  841,  676,  846,
      534,  561,  649,  850,  854,  863,  876,  297,  295,  254,
      885,  891,  900,  922,  930,  939,  961,  969,  978, 1000,
      274,  265,  453,  221,  547,  188,  548,  139,  136,  120,
       49, 1008, 1017, 1039, 1047,  533, 1228,   75, 1228, 1056,
      559, 1228, 1228, 1098, 1109, 1120, 1125, 1131, 1138, 1149,

     1160, 1166, 1168, 1174, 1185, 1191, 1196, 1201, 1207, 1212,
     1217
    } ;

static const flex_int16_t yy_def[312] =
    {   0,
      293,    1,  294,  294,  295,  295,  293,  293,  293,  293,
      293,  296,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      297,  298,  293,  293,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      293,  293,  293,  293,  300,  300,  301,  293,  293,  293,
      293,  293,  296,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  302,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  303,  304,  298,  293,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,

      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  293,  293,  300,  300,  301,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  305,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  306,  307,  293,  293,
      293,  293,  307,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  308,  304,  293,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  293,
      300,  293,  305,  309,  293,  293,  293,  293,  293,  293,

      293,  293,  293,  293,  293,  293,  293,  306,  310,  311,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  308,  293,  299,  299,
      299,  299,  299,  293,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  293,  300,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  310,  311,  311,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      293,  293,  293,  293,  293,  299,  293,  299,  293,  293,
      299,  293,    0,  293,  293,  293,  293,  293,  293,  293,

      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293
    } ;

static const flex_int16_t yy_nxt[1291] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   24,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   32,   32,   32,
       32,   32,   32,   33,    8,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   42,   43,   42,   42,   44,   45,
       42,   42,   46,   47,   48,   49,   42,   50,   42,   51,
       52,   53,    8,    8,  293,   58,   59,    8,   89,   58,
       59,   66,  293,   67,   67,   67,   67,  293,  293,  293,
      293,  293,   77,   56,   78,   79,   79,   79,  293,  293,
      293,   91,  293,   84,   68,  293,   60,  289,   80,   92,

       60,  293,  293,  113,  100,   81,   93,   95,  293,  115,
       80,   94,  293,  104,  293,   96,  101,  105,  102,  293,
      107,   61,   89,   61,  103,   61,  110,   61,   69,  106,
       70,   70,   70,  293,  111,   97,   98,  112,  172,   99,
      108,  171,   71,   72,   73,   91,   74,   75,  293,  293,
      293,   76,  293,   71,  109,   72,   73,   89,  180,  134,
      135,  135,  135,  293,   74,  142,  142,  142,   67,   67,
       67,   67,  173,   75,  120,  137,  137,  137,  137,  174,
      136,  138,  138,  138,  293,  143,  121,  121,  121,   68,
      140,  140,  144,  293,  144,   70,   70,   70,  145,  145,

      145,  293,  139,  175,  293,  122,  293,  293,  123,  124,
      293,  141,  125,  126,  293,  293,  146,  293,  177,  127,
      176,  293,  293,  128,  129,  130,  178,  131,  293,  132,
      149,  149,  149,  154,  293,  155,  155,  155,  155,  293,
      179,  181,  150,  151,  184,  182,  152,  153,  293,  156,
      186,   76,  185,  150,  230,  151,  157,  293,  183,  234,
      293,  156,  188,  158,  152,   78,   78,   78,   78,  293,
      187,  189,   77,  153,   78,   79,   79,   79,  293,   80,
      192,  192,  192,  293,  200,  200,  159,  293,   80,  229,
      259,   80,  231,  235,  163,   81,  164,  164,  164,  164,

       80,  144,  293,  144,  160,  201,  161,  162,  162,  162,
      156,  170,  238,   67,   67,   67,   67,  165,  202,  202,
      156,   89,  156,  134,  135,  135,  135,  160,  145,  145,
      145,  259,  156,  209,   68,  194,  194,  194,  194,  141,
      293,  281,  236,  293,  136,  293,  194,  194,  194,  194,
       89,  293,  134,  135,  135,  135,  293,  194,  194,  194,
      194,  194,  194,   89,  293,  196,  196,  196,  196,  137,
      137,  137,  137,  136,  274,  138,  138,  138,  198,  198,
      198,  293,  237,   73,  239,  293,  136,  205,  205,  205,
      197,  203,  203,  203,  203,   73,  139,  202,  202,  199,

      206,  206,  206,  206,  149,  149,  149,  143,  211,  211,
      211,  293,  204,  205,  205,  205,  240,  242,  141,  293,
      293,  207,  149,  149,  149,  146,  246,  246,  246,  199,
      200,  200,  212,  143,  213,  213,  213,  213,  293,  241,
      293,  293,  163,  146,  215,  216,  216,  216,  156,  293,
      293,  201,  293,  243,  275,  214,  293,  195,   80,  160,
      156,  161,  218,  218,  218,  217,  293,  259,  276,  214,
       80,  219,  219,  219,  219,  156,  271,  232,  272,  259,
      280,  233,  160,  251,  251,  156,  214,  156,  220,  220,
      220,  220,  157,  293,  286,  277,  214,  156,  164,  164,

      164,  164,  156,  160,  252,  161,  218,  218,  218,  214,
      253,  253,  156,  160,  156,  161,  218,  218,  218,  221,
      250,  250,  250,  250,  156,  222,  160,  223,  224,  224,
      224,  252,  278,  209,  293,  154,  160,  219,  219,  219,
      219,  156,  257,  257,  257,  257,  293,  293,  225,  251,
      251,  156,  158,  156,  164,  164,  164,  164,  157,  245,
      293,  293,  163,  156,  226,  226,  226,  226,   80,  273,
      201,  287,  293,  291,  244,  159,  253,  253,  156,  293,
       80,  279,  293,  292,  248,  165,   67,   67,   67,   67,
      156,  293,  293,  293,  293,  293,  288,  252,  196,  196,

      196,  196,  293,  293,  293,  293,  293,   68,  198,  198,
      198,  293,  228,  293,  293,  293,  293,  293,  293,  249,
      211,  211,  211,  203,  203,  203,  203,  148,  148,  139,
      254,  254,  254,  254,  256,  256,  256,  256,  211,  211,
      211,  199,  209,  195,  204,  206,  206,  206,  206,  191,
      190,  255,  293,  293,  293,  255,  293,  293,  261,  199,
      213,  213,  213,  213,  253,  253,  207,  214,  167,  213,
      213,  213,  213,  214,  156,  213,  213,  213,  213,  166,
      148,  214,  133,  156,  119,  252,  156,  117,  114,  156,
      214,  196,  196,  196,  196,  156,  214,  293,   86,   85,

      163,  156,  215,  216,  216,  216,  163,   84,  215,  216,
      216,  216,  249,   83,   82,  163,   80,  262,  262,  262,
      262,   65,   80,  217,   64,   62,  293,    8,   80,  217,
       54,  156,  293,  293,   80,  293,  293,  222,  263,  264,
      265,  265,  265,  156,  293,  163,  293,  266,  267,  267,
      267,  293,  293,  156,  214,  293,  220,  220,  220,  220,
      222,  156,  293,  293,  293,  156,  293,  293,  263,  293,
       80,  293,  293,  156,  293,  293,  214,  268,  226,  226,
      226,  226,   80,  293,  222,  293,  264,  265,  265,  265,
      293,  293,  156,  222,  293,  223,  224,  224,  224,  221,

      156,  293,  293,  293,  156,  293,  293,  222,  293,  156,
      293,  293,  156,  293,  293,  222,  225,  223,  224,  224,
      224,  156,  293,  222,  293,  269,  270,  270,  270,  293,
      293,  156,  214,  293,  226,  226,  226,  226,  225,  156,
      293,  293,  293,  156,  293,  293,  222,  293,  156,  293,
      293,  156,  293,  293,  248,  221,   67,   67,   67,   67,
      156,  250,  250,  250,  250,  254,  254,  254,  254,  256,
      256,  256,  256,  293,  293,   73,  293,   68,  256,  256,
      256,  256,  197,  293,  293,  293,  204,   73,  293,  293,
      255,  257,  257,  257,  257,  293,  293,  293,  282,  255,

      219,  219,  219,  219,  214,  293,  262,  262,  262,  262,
      293,  293,  207,  163,  156,  284,  284,  284,  284,  293,
       80,  157,  293,  293,  293,  293,  156,  283,  293,  156,
      293,  293,   80,  293,  293,  222,  263,  264,  265,  265,
      265,  156,  293,  222,  293,  264,  265,  265,  265,  293,
      293,  156,  163,  293,  266,  267,  267,  267,  222,  156,
      293,  293,  293,  156,  293,  293,  222,  293,  156,  293,
      293,  156,  293,  293,  163,  263,  266,  267,  267,  267,
      156,  293,  214,  293,  285,  285,  285,  285,  293,  293,
      156,  222,  293,  269,  270,  270,  270,  263,  156,  293,

      293,  293,  156,  293,  293,  214,  293,  156,  293,  293,
      156,  293,  293,  222,  225,  269,  270,  270,  270,  156,
      293,  282,  293,  219,  219,  219,  219,  293,  293,  156,
      214,  293,  262,  262,  262,  262,  225,  156,  293,  293,
      293,  156,  293,  293,  157,  293,  156,  293,  293,  156,
      293,  293,  214,  290,  284,  284,  284,  284,  156,  293,
      214,  293,  285,  285,  285,  285,  293,  293,  156,  214,
      293,  284,  284,  284,  284,  290,   80,  293,  293,  293,
      156,  293,  293,  268,  293,  156,  293,  293,   80,  293,
      293,  293,  290,  293,  293,  293,  293,  156,   55,   55,

       55,   55,   55,   55,   55,   55,   55,   55,   55,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       63,  293,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   87,  293,   87,   87,   87,   88,  293,   88,   88,
       88,   88,   90,   90,  293,   90,   90,   90,   90,  116,
      293,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      118,  293,  293,  293,  118,  118,  118,  118,  118,  118,
      118,  147,  293,  293,  147,  147,  168,  168,  168,  169,
      293,  169,  169,  169,  169,  193,  293,  293,  193,  193,
      193,  193,  193,  193,  193,  193,  208,  293,  293,  208,

      208,  210,  293,  293,  210,  210,  227,  293,  227,  227,
      227,  227,  247,  293,  293,  293,  247,  258,  293,  293,
      258,  258,  260,  293,  293,  260,  260,    7,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293
    } ;

static const flex_int16_t yy_chk[1291] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    4,    5,   36,    5,    5,    6,   35,    6,
        6,   21,   50,   21,   21,   21,   21,   38,   37,   39,
       41,   44,   24,    4,   24,   24,   24,   24,  288,   43,
       45,   35,   46,   54,   21,   48,    5,  281,   24,   36,

        6,   40,   49,   50,   41,   24,   37,   39,   93,   54,
       24,   38,   47,   44,   92,   39,   41,   44,   43,  101,
       46,    5,   91,    5,   43,    6,   48,    6,   23,   45,
       23,   23,   23,  280,   48,   40,   40,   49,   93,   40,
       47,   92,   23,   23,   23,   91,   23,   23,   94,  279,
       95,   23,  278,   23,   47,   23,   23,   67,  101,   67,
       67,   67,   67,   97,   23,   72,   72,   72,   68,   68,
       68,   68,   94,   23,   60,   69,   69,   69,   69,   95,
       67,   70,   70,   70,   99,   72,   60,   60,   60,   68,
       71,   71,   73,   98,   73,   74,   74,   74,   73,   73,

       73,  276,   70,   97,  105,   60,  100,  104,   60,   60,
      108,   71,   60,   60,  173,  109,   74,  107,   99,   60,
       98,  112,  110,   60,   60,   60,   99,   60,  111,   60,
       76,   76,   76,   77,  274,   77,   77,   77,   77,  113,
      100,  104,   76,   76,  108,  105,   76,   76,  177,   77,
      110,   76,  109,   76,  173,   76,   77,  172,  107,  177,
      174,   77,  112,   78,   76,   78,   78,   78,   78,  178,
      111,  113,   79,   76,   79,   79,   79,   79,  272,   78,
      121,  121,  121,  184,  140,  140,   78,  271,   79,  172,
      260,   78,  174,  178,   81,   79,   81,   81,   81,   81,

       79,   80,  179,   80,   80,  140,   80,   80,   80,   80,
       81,   89,  184,   89,   89,   89,   89,   81,  141,  141,
       80,  134,   81,  134,  134,  134,  134,   80,  144,  144,
      144,  259,   80,  258,   89,  132,  132,  132,  132,  141,
      183,  244,  179,  241,  134,  233,  132,  132,  132,  132,
      135,  240,  135,  135,  135,  135,  185,  132,  132,  132,
      132,  132,  132,  136,  238,  136,  136,  136,  136,  137,
      137,  137,  137,  135,  233,  138,  138,  138,  139,  139,
      139,  186,  183,  137,  185,  188,  136,  143,  143,  143,
      137,  142,  142,  142,  142,  137,  138,  150,  150,  139,

      145,  145,  145,  145,  146,  146,  146,  143,  149,  149,
      149,  187,  142,  151,  151,  151,  186,  188,  150,  189,
      235,  145,  152,  152,  152,  146,  192,  192,  192,  149,
      200,  200,  154,  151,  154,  154,  154,  154,  230,  187,
      236,  229,  155,  152,  155,  155,  155,  155,  154,  175,
      232,  200,  243,  189,  235,  154,  237,  228,  155,  156,
      154,  156,  156,  156,  156,  155,  273,  210,  236,  157,
      155,  157,  157,  157,  157,  156,  229,  175,  230,  209,
      243,  175,  156,  201,  201,  157,  158,  156,  158,  158,
      158,  158,  157,  239,  273,  237,  159,  157,  159,  159,

      159,  159,  158,  160,  201,  160,  160,  160,  160,  158,
      202,  202,  159,  161,  158,  161,  161,  161,  161,  159,
      197,  197,  197,  197,  159,  162,  160,  162,  162,  162,
      162,  202,  239,  208,  231,  163,  161,  163,  163,  163,
      163,  162,  207,  207,  207,  207,  286,  242,  162,  251,
      251,  163,  164,  162,  164,  164,  164,  164,  163,  191,
      275,  277,  165,  163,  165,  165,  165,  165,  164,  231,
      251,  275,  291,  286,  190,  164,  252,  252,  165,  182,
      164,  242,  181,  291,  195,  165,  195,  195,  195,  195,
      165,  193,  193,  193,  193,  180,  277,  252,  196,  196,

      196,  196,  193,  193,  193,  193,  176,  195,  198,  198,
      198,  171,  170,  193,  193,  193,  193,  193,  193,  196,
      199,  199,  199,  203,  203,  203,  203,  153,  148,  198,
      204,  204,  204,  204,  205,  205,  205,  205,  211,  211,
      211,  199,  147,  133,  203,  206,  206,  206,  206,  117,
      115,  204,  106,  103,  102,  205,   96,   90,  212,  211,
      212,  212,  212,  212,  253,  253,  206,  213,   84,  213,
      213,  213,  213,  214,  212,  214,  214,  214,  214,   83,
       75,  212,   66,  213,   59,  253,  212,   56,   52,  214,
      213,  249,  249,  249,  249,  213,  214,   42,   31,   29,

      215,  214,  215,  215,  215,  215,  216,   28,  216,  216,
      216,  216,  249,   27,   25,  217,  215,  217,  217,  217,
      217,   17,  216,  215,   14,   10,    7,    3,  215,  216,
        2,  217,    0,    0,  216,    0,    0,  218,  217,  218,
      218,  218,  218,  217,    0,  219,    0,  219,  219,  219,
      219,    0,    0,  218,  220,    0,  220,  220,  220,  220,
      218,  219,    0,    0,    0,  218,    0,    0,  219,    0,
      220,    0,    0,  219,    0,    0,  221,  220,  221,  221,
      221,  221,  220,    0,  222,    0,  222,  222,  222,  222,
        0,    0,  221,  223,    0,  223,  223,  223,  223,  221,

      222,    0,    0,    0,  221,    0,    0,  222,    0,  223,
        0,    0,  222,    0,    0,  224,  223,  224,  224,  224,
      224,  223,    0,  225,    0,  225,  225,  225,  225,    0,
        0,  224,  226,    0,  226,  226,  226,  226,  224,  225,
        0,    0,    0,  224,    0,    0,  225,    0,  226,    0,
        0,  225,    0,    0,  248,  226,  248,  248,  248,  248,
      226,  250,  250,  250,  250,  254,  254,  254,  254,  255,
      255,  255,  255,    0,    0,  250,    0,  248,  256,  256,
      256,  256,  250,    0,    0,    0,  254,  250,    0,    0,
      255,  257,  257,  257,  257,    0,    0,    0,  261,  256,

      261,  261,  261,  261,  262,    0,  262,  262,  262,  262,
        0,    0,  257,  263,  261,  263,  263,  263,  263,    0,
      262,  261,    0,    0,    0,    0,  261,  262,    0,  263,
        0,    0,  262,    0,    0,  264,  263,  264,  264,  264,
      264,  263,    0,  265,    0,  265,  265,  265,  265,    0,
        0,  264,  266,    0,  266,  266,  266,  266,  264,  265,
        0,    0,    0,  264,    0,    0,  265,    0,  266,    0,
        0,  265,    0,    0,  267,  266,  267,  267,  267,  267,
      266,    0,  268,    0,  268,  268,  268,  268,    0,    0,
      267,  269,    0,  269,  269,  269,  269,  267,  268,    0,

        0,    0,  267,    0,    0,  268,    0,  269,    0,    0,
      268,    0,    0,  270,  269,  270,  270,  270,  270,  269,
        0,  282,    0,  282,  282,  282,  282,    0,    0,  270,
      283,    0,  283,  283,  283,  283,  270,  282,    0,    0,
        0,  270,    0,    0,  282,    0,  283,    0,    0,  282,
        0,    0,  284,  283,  284,  284,  284,  284,  283,    0,
      285,    0,  285,  285,  285,  285,    0,    0,  284,  290,
        0,  290,  290,  290,  290,  284,  285,    0,    0,    0,
      284,    0,    0,  285,    0,  290,    0,    0,  285,    0,
        0,    0,  290,    0,    0,    0,    0,  290,  294,  294,

      294,  294,  294,  294,  294,  294,  294,  294,  294,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      296,    0,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  297,    0,  297,  297,  297,  298,    0,  298,  298,
      298,  298,  299,  299,    0,  299,  299,  299,  299,  300,
        0,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      301,    0,    0,    0,  301,  301,  301,  301,  301,  301,
      301,  302,    0,    0,  302,  302,  303,  303,  303,  304,
        0,  304,  304,  304,  304,  305,    0,    0,  305,  305,
      305,  305,  305,  305,  305,  305,  306,    0,    0,  306,

      306,  307,    0,    0,  307,  307,  308,    0,  308,  308,
      308,  308,  309,    0,    0,    0,  309,  310,    0,    0,
      310,  310,  311,    0,    0,  311,  311,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[100] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "RubyLexer.l"
#line 6 "RubyLexer.l"
	#include <stdio.h>
    #include "tree_nodes.h"
    #include "parser.tab.h"    

    void removeCharacterFromString(const char * str, char * dest, char deleted_char);
    int binstrToDec(const char * str);
#line 865 "lex.yy.c"

#line 867 "lex.yy.c"

#define INITIAL 0
#define ML_COMMENT 1
#define STRING 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 29 "RubyLexer.l"


   
#line 33 "RubyLexer.l"
    int num;
    float real_num;
    char temp1[100];
    char temp2[100];
    char comment[1000];
    char string[1000];
    int concatenation = 0;


#line 1103 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 294 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 293 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 42 "RubyLexer.l"
{ return AND; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 43 "RubyLexer.l"
{ return BEGIN; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 44 "RubyLexer.l"
{ return CLASS; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 45 "RubyLexer.l"
{ return DEF; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "RubyLexer.l"
{ return DEFINED; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 47 "RubyLexer.l"
{ return DO; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 48 "RubyLexer.l"
{ return IF; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 49 "RubyLexer.l"
{ return ELSE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 50 "RubyLexer.l"
{ return ELSIF; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 51 "RubyLexer.l"
{ return END; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 52 "RubyLexer.l"
{ return FALSE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 53 "RubyLexer.l"
{ return FOR; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 54 "RubyLexer.l"
{ return IN; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 55 "RubyLexer.l"
{ return NIL; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 56 "RubyLexer.l"
{ return NOT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 57 "RubyLexer.l"
{ return OR; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 58 "RubyLexer.l"
{ return RETURN; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 59 "RubyLexer.l"
{ return SELF; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 60 "RubyLexer.l"
{ return SUPER; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 61 "RubyLexer.l"
{ return THEN; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 62 "RubyLexer.l"
{ return TRUE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 63 "RubyLexer.l"
{ return UNTIL; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 64 "RubyLexer.l"
{ return WHILE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 66 "RubyLexer.l"
{ return ARITHMETIC_PLUS_OP; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 67 "RubyLexer.l"
{ return ARITHMETIC_MINUS_OP; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 68 "RubyLexer.l"
{ return ARITHMETIC_MUL_OP; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 69 "RubyLexer.l"
{ return ARITHMETIC_DIV_OP; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 70 "RubyLexer.l"
{ return ARITHMETIC_MOD_OP; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 71 "RubyLexer.l"
{ return ARITHMETIC_POW_OP; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 73 "RubyLexer.l"
{ return EQL_OP; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 74 "RubyLexer.l"
{ return NOT_EQL_OP; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 75 "RubyLexer.l"
{ return GREATER_OP; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 76 "RubyLexer.l"
{ return LESS_OP; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 77 "RubyLexer.l"
{ return GREATER_OR_EQL_OP; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 78 "RubyLexer.l"
{ return LESS_OR_EQL_OP; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 79 "RubyLexer.l"
{ return COMB_COMPRASION_OP; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 80 "RubyLexer.l"
{ return CASE_EQL_OP; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 81 "RubyLexer.l"
{ return RECEIVER_EQL_OP; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 82 "RubyLexer.l"
{ return OBJ_ID_EQL_OP; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 84 "RubyLexer.l"
{ return ASSIGN_OP; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 86 "RubyLexer.l"
{ return LOGICAL_AND_OP; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 87 "RubyLexer.l"
{ return LOGICAL_OR_OP; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 88 "RubyLexer.l"
{ return LOGICAL_NOT_OP; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 90 "RubyLexer.l"
{ return INCLUSIVE_RANGE_OP; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 91 "RubyLexer.l"
{ return EXCLUSIVE_RANGE_OP; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 93 "RubyLexer.l"
{ return QUESTION_SYMBOL; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 94 "RubyLexer.l"
{ return DOT_SYMBOL; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 95 "RubyLexer.l"
{ return COMMA_SYMBOL; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 96 "RubyLexer.l"
{ return COLON_SYMBOL; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 97 "RubyLexer.l"
{ return DOUBLE_COLON_SYMBOL; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 98 "RubyLexer.l"
{ return SEMICOLON_SYMBOL; }
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 99 "RubyLexer.l"
{ return NEW_LINE_SYMBOL;  }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 100 "RubyLexer.l"
{ return OPEN_ROUND_BRACKET; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 101 "RubyLexer.l"
{ return CLOSE_ROUND_BRACKET; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 102 "RubyLexer.l"
{ return OPEN_CURLY_BRACKET; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 103 "RubyLexer.l"
{
                if(concatenation == 0) {
                    return CLOSE_CURLY_BRACKET;
                } else {
                    concatenation--;
                    BEGIN(STRING);
                    string[0] = 0;
                    return ARITHMETIC_PLUS_OP;
                }
            }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 113 "RubyLexer.l"
{ return OPEN_SQUARE_BRACKET; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 114 "RubyLexer.l"
{ return CLOSE_SQUARE_BRACKET; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 116 "RubyLexer.l"
{ 
                string[0] = 0; 
                BEGIN(STRING);    
            }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 121 "RubyLexer.l"
{                         
                        concatenation++;
                        BEGIN(INITIAL);
                    }            
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 126 "RubyLexer.l"
{ strcat(string, yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 127 "RubyLexer.l"
{ strcat(string, yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 128 "RubyLexer.l"
{ strcat(string, "\n"); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 129 "RubyLexer.l"
{ strcat(string, "\a"); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 130 "RubyLexer.l"
{ strcat(string, "\b"); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 131 "RubyLexer.l"
{ strcat(string, "\t"); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 132 "RubyLexer.l"
{ strcat(string, "\v"); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 133 "RubyLexer.l"
{ strcat(string, "\f"); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 134 "RubyLexer.l"
{ strcat(string, "\r"); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 135 "RubyLexer.l"
{ strcat(string, "\e"); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 136 "RubyLexer.l"
{ strcat(string, " "); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 137 "RubyLexer.l"
{ strcat(string, "\\"); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 138 "RubyLexer.l"
{ strcat(string, "\""); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 139 "RubyLexer.l"
{ 
                                sscanf(yytext + 1, "%o", &num);
                                temp1[0] = (char) num;
                                temp1[1] = 0;
                                strcat(string, temp1);
                            }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 146 "RubyLexer.l"
{ 
                                sscanf(yytext + 2, "%x", &num);
                                temp1[0] = (char) num;
                                temp1[1] = 0;
                                strcat(string, temp1);
                            }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 152 "RubyLexer.l"
{ printf("ERROR: invalid hex escape \n"); } 
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 153 "RubyLexer.l"
{ printf("ERROR: expected \" \n");}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 154 "RubyLexer.l"
{ 
                yylval.string_un=(char *)malloc(strlen(string)+1);
                strcpy(yylval.string_un, string);
                BEGIN(INITIAL);
                return STRING;
            }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 161 "RubyLexer.l"
{ printf("Single-line comment: %s\n", yytext + 1); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 163 "RubyLexer.l"
{                                     
                            comment[0] = 0; 
                            BEGIN(ML_COMMENT);
                        }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 168 "RubyLexer.l"
{
                            strcat(comment, yytext + 5);
                            printf("Multi-line comment: %s\n", comment);
                            BEGIN(INITIAL);
                        }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 174 "RubyLexer.l"
{ 
                            strcat(comment, yytext); 
                        }
	YY_BREAK
case YY_STATE_EOF(ML_COMMENT):
#line 178 "RubyLexer.l"
{ 
                            printf("expected =end"); BEGIN(INITIAL); 
                        }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 182 "RubyLexer.l"
{ 
                                removeCharacterFromString(yytext,temp1,'_');
                                yylval.int_un = atoi(temp1);
                                return INTEGER_NUMBER;
                            }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 188 "RubyLexer.l"
{ printf("ERROR: invalid decimal number: %s\n", yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 190 "RubyLexer.l"
{
                                removeCharacterFromString(yytext+2,temp1,'_');
                                yylval.int_un = atoi(temp1);
                                return INTEGER_NUMBER;              
                            }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 196 "RubyLexer.l"
{ printf("ERROR: invalid decimal number with dD: %s\n", yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 198 "RubyLexer.l"
{
                                removeCharacterFromString(yytext,temp1,'_');
                                removeCharacterFromString(temp1,temp2,'o');
                                removeCharacterFromString(temp2,temp1,'O');
                                yylval.int_un = num;
                                return INTEGER_NUMBER;
                            }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 206 "RubyLexer.l"
{ printf("ERROR: invalid octal number: %s\n", yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 208 "RubyLexer.l"
{
                                removeCharacterFromString(yytext + 2,temp1,'_');
                                yylval.int_un = num;
                                return INTEGER_NUMBER;
                            }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 214 "RubyLexer.l"
{ printf("ERROR: invalid hexadecimal number: %s\n", yytext); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 216 "RubyLexer.l"
{
                                removeCharacterFromString(yytext + 2,temp1,'_');
                                yylval.int_un = num;
                                return INTEGER_NUMBER; 
                            }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 222 "RubyLexer.l"
{ printf("ERROR: invalid binary number: %s\n", yytext); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 225 "RubyLexer.l"
{
                                                                removeCharacterFromString(yytext,temp1,'_');                                                                  
                                                                real_num = (float) atof(temp1);
                                                                yylval.float_un = (float) real_num;
                                                                return FLOAT_NUMBER;
                                                            }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 231 "RubyLexer.l"
{ printf("ERROR: invalid float number: %s\n", yytext); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 232 "RubyLexer.l"
{ printf("ERROR: invalid float number with eE: %s\n", yytext); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 234 "RubyLexer.l"
{
                                                yylval.string_un=(char *)malloc(strlen(yytext)+1);
                                                strcpy(yylval.string_un, yytext); 
                                                return VAR_OR_METHOD_NAME;
                                            }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 240 "RubyLexer.l"
{
                                                yylval.string_un=(char *)malloc(strlen(yytext)+1);
                                                strcpy(yylval.string_un, yytext); 
                                                return INSTANCE_VAR_NAME;
                                            }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 246 "RubyLexer.l"
{
                                                yylval.string_un=(char *)malloc(strlen(yytext)+1);
                                                strcpy(yylval.string_un, yytext); 
                                                return CLASS_VAR_NAME;
                                            }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 252 "RubyLexer.l"
{
                                                yylval.string_un=(char *)malloc(strlen(yytext)+1);
                                                strcpy(yylval.string_un, yytext); 
                                                return CLASS_NAME;
                                            }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 258 "RubyLexer.l"
ECHO;
	YY_BREAK
#line 1755 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 294 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 294 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 293);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 258 "RubyLexer.l"


void removeCharacterFromString(const char * str, char * dest, char deleted_char) {
	int j = 0;
	
    for(int i = 0; str[i] != 0; i++) {
        if(str[i] != deleted_char) {
            dest[j++] = str[i];
        }
    }

    dest[j] = 0;
}

int binstrToDec(const char * str) {
    unsigned char *p = str;
    unsigned int   r = 0;

    while (p && *p ) {
        r <<= 1;
        r += (unsigned int)((*p++) & 0x01);
    }

    return (int) r;
}
