
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 91
#define YY_END_OF_BUFFER 92
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[273] =
    {   0,
        0,    0,   73,   73,    0,    0,   92,   91,   44,   38,
       51,   70,   25,   91,   45,   46,   23,   21,   42,   22,
       41,   24,   74,   74,   43,   30,   35,   29,   91,   90,
       49,   50,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   47,   91,   48,
       35,   73,   73,   53,   69,   54,   91,   54,   28,   70,
       36,   26,   39,   85,    0,    0,   78,    0,    0,    0,
        0,    0,    0,    0,   74,   74,   86,   75,   32,   27,
       31,    0,   88,   90,    0,   87,   87,   87,   87,   87,
        5,   87,   87,   87,   87,    6,   12,   87,   14,   87,

       87,   87,   87,   87,   87,   37,    0,   73,   73,   53,
       52,   65,   66,   64,   56,   57,   62,   60,   55,   61,
       63,   58,   59,   68,   40,   85,   85,   85,   84,   78,
       79,   82,    0,   76,    0,    0,   84,    0,   80,    0,
       79,    0,    0,    0,    0,    0,   84,   86,    0,    0,
       75,   86,   86,   84,    0,   74,   75,   33,   34,   89,
       88,    0,    1,   87,    3,   87,    9,   87,   11,   13,
       87,   87,   87,   87,   87,   87,    0,   73,   66,   68,
       67,    0,   85,    0,   78,   79,   82,   83,   83,   76,
       77,   77,   84,    0,   80,   81,   81,   79,    0,    0,

        0,   84,   84,   85,   86,   85,   84,   75,   86,   84,
       84,   86,   75,   89,    0,   87,   87,    7,   87,   87,
       87,   16,   17,   18,   87,   87,    0,   72,   66,   67,
        0,   85,   84,   82,   83,   83,   76,   77,   77,   84,
       80,   81,   81,    0,   84,   85,   86,   86,   85,   85,
        0,   84,   84,    2,   87,    8,   10,   87,   19,   20,
        0,    0,   85,   85,   84,   87,   15,   71,   85,   87,
        4,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   19,   19,    1,   20,   21,
       22,   23,   24,   25,   26,   27,   26,   28,   29,   26,
       30,   30,   30,   30,   30,   30,   30,   30,   31,   30,
       30,   30,   30,   30,   30,   30,   30,   32,   30,   30,
       33,   34,   35,    1,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   46,   46,   47,   46,   48,
       49,   46,   46,   50,   51,   52,   53,   54,   55,   56,
       46,   46,   57,   58,   59,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[60] =
    {   0,
        1,    2,    1,    3,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    1,    6,    6,    6,    6,    1,
        1,    1,    1,    1,    7,    6,    6,    6,    6,    8,
        8,    8,    1,    4,    1,    9,   10,   10,   10,   10,
       10,   10,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,    4,    1,    4
    } ;

static const flex_int16_t yy_base[291] =
    {   0,
        0,  641,  658,   58,   59,   63,  658, 1198, 1198,  634,
     1198,    0, 1198,  644, 1198, 1198,  635, 1198, 1198, 1198,
       55, 1198,  109,   65, 1198,  612,  611,  609,  605,    0,
     1198, 1198,   52,   48,  615,   56,   61,   64,   72,   71,
       75,   78,   63,   73,   85,   84,   86, 1198,  569, 1198,
       93,    0,  580,    0, 1198,  563,  162, 1198, 1198,    0,
     1198, 1198,  596,  137,  145,  151,  158,  155,  165,  204,
      169,  559,  208,  213,  242,  251,  282,  288,  566,  562,
     1198,    0,    0,    0,  258,  568,   81,   93,  120,  146,
      567,   91,  179,  130,  145,  566,  554,   94,  553,  138,

      194,  192,  175,  193,  206, 1198,  517,    0,  509,    0,
     1198, 1198,  268, 1198, 1198, 1198, 1198, 1198, 1198, 1198,
     1198, 1198, 1198,  314,  542,  330,  343,  351,  309,  272,
      298,  246,  303,  355,  358,  318,  364,  368,  518,  507,
      372,  376,  378,  385,  506,  399,  408,  429,  437,  443,
      469,  475,  483,  498,  504,  512,  533, 1198, 1198,    0,
        0,  518,  499,  183,  236,  364,  490,  252,  489,  482,
      184,  392,  195,  197,  265,  384,  452,  442,  451,  559,
        0,  547,  519,  458,  554,  575,  394,  403,  416,  586,
      590,  596,  600,  490,  445,  444,  406,  607,  621,  630,

      651,  659,  665,  691,  697,  705,  726,  734,  740,  766,
      772,  780,  801,    0,  415,  307,  393,  385,  422,  409,
      241,  350,  349,  308,  424,  449,  268,    0, 1198, 1198,
      808,  636,  816,  508,  543,  625,  787,  822,  830,  837,
      276,  273,  261,  845,  851,  877,  883,  891,  912,  920,
      926,  952,  958,  239,  532,  238,  134,  580,  129,  125,
       42,  966,  987,  995, 1001,  233,   62, 1198, 1027,  178,
     1198, 1198, 1068, 1079, 1090, 1095, 1101, 1108, 1119, 1130,
     1136, 1138, 1144, 1155, 1161, 1166, 1171, 1177, 1182, 1187
    } ;

static const flex_int16_t yy_def[291] =
    {   0,
      272,    1,  273,  273,  274,  274,  272,  272,  272,  272,
      272,  275,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  276,  277,
      272,  272,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  272,  272,  272,
      272,  279,  279,  280,  272,  272,  272,  272,  272,  275,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  281,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  282,  283,  277,  272,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,

      278,  278,  278,  278,  278,  272,  272,  279,  279,  280,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  284,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  285,  286,
      272,  272,  272,  272,  286,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  287,
      283,  272,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  272,  279,  272,  284,
      288,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  285,  289,  290,  272,  272,  272,

      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  287,  272,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  272,  279,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      289,  290,  290,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  278,  278,  278,  278,  278,  278,  278,
      272,  272,  272,  272,  272,  278,  278,  272,  272,  278,
      272,    0,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272
    } ;

static const flex_int16_t yy_nxt[1258] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   24,   24,   25,
       26,   27,   28,    8,   29,   30,   30,   30,   30,   30,
       30,   30,   31,    8,   32,   33,   34,   35,   36,   37,
       38,   39,   35,   35,   40,   35,   35,   41,   42,   43,
       44,   45,   46,   35,   47,   35,   48,   49,   50,    8,
        8,  272,   55,   56,    8,   85,   55,   56,   63,  272,
       64,   64,   64,   64,  272,  272,  272,  272,   74,   53,
       75,   76,   76,   76,  272,  272,  272,   87,  272,  268,
       65,  272,   57,   77,   85,   88,   57,  272,  272,  272,

       78,   90,   89,  100,  272,   77,  272,  272,   94,   91,
       92,   93,   96,  101,   80,   58,   87,   58,   97,   58,
       95,   58,   66,   98,   67,   67,   67,   99,  102,  105,
      107,  104,  163,  272,  103,   68,   69,   70,  272,   71,
       72,  166,  272,  272,   73,  170,   68,  272,   69,   70,
       85,  272,  126,  127,  127,  127,  164,   71,  272,  272,
       64,   64,   64,   64,   72,  112,  129,  129,  129,  129,
      132,  132,  128,  130,  130,  130,  168,  113,  113,  113,
       65,  134,  134,  134,   67,   67,   67,  165,  272,  171,
      133,  272,  272,  131,  169,  114,  272,  272,  115,  116,

      135,  271,  117,  118,  138,  272,  272,  272,  272,  119,
      272,  120,  121,  122,  136,  123,  136,  124,  167,  272,
      137,  137,  137,  141,  141,  141,  146,  174,  147,  147,
      147,  147,  173,  216,  142,  143,  221,  224,  144,  145,
      172,  148,  223,   73,  175,  142,  272,  143,  149,  272,
      176,  272,  272,  148,  272,  150,  144,   75,   75,   75,
       75,  187,  187,  145,   74,  272,   75,   76,   76,   76,
       77,  162,  270,   64,   64,   64,   64,  151,  272,   77,
      217,  188,   77,  179,  179,  179,   78,  130,  130,  130,
      258,   77,  136,   65,  136,  152,  242,  153,  154,  154,

      154,  155,  220,  156,  156,  156,  156,  131,  242,  225,
      148,  196,  261,  185,  185,  185,  148,  152,  189,  189,
      272,  272,  148,  157,  129,  129,  129,  129,  148,  181,
      181,  181,  181,  186,  137,  137,  137,   70,  133,  181,
      181,  181,  181,   85,  184,  126,  127,  127,  127,   70,
      181,  181,  181,  181,  181,  181,   85,  254,  126,  127,
      127,  127,  272,  272,   85,  128,  183,  183,  183,  183,
      190,  190,  190,  190,  192,  192,  192,  272,  128,  193,
      193,  193,  193,  141,  141,  141,  128,  198,  198,  198,
      191,  189,  189,  135,  192,  192,  192,  272,  272,  194,

      141,  141,  141,  138,  218,  272,  272,  186,  219,  187,
      187,  133,  199,  135,  200,  200,  200,  200,  234,  234,
      138,  155,  272,  202,  203,  203,  203,  148,  182,  188,
      226,  236,  236,  222,  201,  272,   77,  272,  235,  148,
      255,  242,  152,  204,  153,  205,  205,  205,   77,  257,
      201,  235,  206,  206,  206,  206,  201,  148,  207,  207,
      207,  207,  272,  256,  152,  148,  229,  229,  229,  148,
      259,  148,  149,  233,  233,  233,  233,  148,  201,  242,
      196,  228,  201,  148,  156,  156,  156,  156,  152,  260,
      153,  205,  205,  205,  227,  272,  152,  148,  153,  205,

      205,  205,  272,  272,  208,  240,  240,  240,  240,  148,
      152,  209,  272,  210,  211,  211,  211,  146,  152,  206,
      206,  206,  206,  234,  234,  150,  148,  156,  156,  156,
      156,  215,  148,  212,  183,  183,  183,  183,  148,  149,
       77,  140,  140,  188,  148,  272,  155,  151,  213,  213,
      213,  213,   77,  196,  232,  182,  178,  177,  236,  236,
      231,  148,   64,   64,   64,   64,  272,  272,  157,  185,
      185,  185,  266,  148,  272,  272,  272,  272,  235,  272,
      272,  272,   65,  159,  272,  272,  272,  272,  158,  131,
      198,  198,  198,  272,  140,  272,  272,  272,  272,  272,

      272,  190,  190,  190,  190,  237,  237,  237,  237,  125,
      186,  239,  239,  239,  239,  193,  193,  193,  193,  111,
      109,  191,  198,  198,  198,  238,  106,  267,  272,   82,
       81,  238,   80,   79,  244,  194,  200,  200,  200,  200,
      236,  236,  186,  201,   62,  200,  200,  200,  200,  148,
       61,  183,  183,  183,  183,   59,  201,  272,  148,    8,
      235,  148,   51,  272,  201,  201,  200,  200,  200,  200,
      148,  232,  155,  272,  202,  203,  203,  203,  155,  148,
      202,  203,  203,  203,  272,  272,  201,   77,  272,  272,
      272,  148,  272,   77,  204,  272,  272,  272,  272,   77,

      204,  272,  272,  272,  155,   77,  245,  245,  245,  245,
      209,  272,  247,  248,  248,  248,  272,  272,  155,  148,
      249,  250,  250,  250,  272,  148,  246,  272,  272,  272,
      272,  148,  209,  148,  272,  272,  272,  148,  272,  201,
      246,  207,  207,  207,  207,  148,  272,  201,  272,  213,
      213,  213,  213,  209,   77,  247,  248,  248,  248,  272,
      272,  251,  148,  272,  272,  272,   77,  272,  148,  208,
      272,  272,  272,  272,  148,  209,  272,  272,  272,  209,
      148,  210,  211,  211,  211,  209,  272,  210,  211,  211,
      211,  272,  272,  209,  148,  252,  253,  253,  253,  272,

      148,  212,  237,  237,  237,  237,  148,  212,  148,  272,
      272,  272,  148,  272,  201,  209,  213,  213,  213,  213,
      148,  231,  191,   64,   64,   64,   64,  272,  272,  148,
      272,  233,  233,  233,  233,  272,  208,  239,  239,  239,
      239,  148,  272,   65,   70,  239,  239,  239,  239,  272,
      272,  184,  240,  240,  240,  240,   70,  238,  262,  272,
      206,  206,  206,  206,  201,  238,  245,  245,  245,  245,
      272,  272,  194,  148,  272,  272,  272,  272,  272,   77,
      149,  272,  272,  272,  272,  148,  263,  272,  272,  272,
      155,   77,  264,  264,  264,  264,  209,  272,  247,  248,

      248,  248,  272,  272,  209,  148,  247,  248,  248,  248,
      272,  148,  246,  272,  272,  272,  272,  148,  209,  148,
      272,  272,  272,  148,  272,  155,  209,  249,  250,  250,
      250,  148,  272,  155,  272,  249,  250,  250,  250,  201,
      148,  265,  265,  265,  265,  272,  272,  246,  148,  272,
      272,  272,  148,  272,  148,  246,  272,  272,  272,  272,
      148,  201,  272,  272,  272,  209,  148,  252,  253,  253,
      253,  209,  272,  252,  253,  253,  253,  272,  272,  262,
      148,  206,  206,  206,  206,  272,  148,  212,  272,  272,
      272,  272,  148,  212,  148,  272,  272,  272,  148,  272,

      201,  149,  245,  245,  245,  245,  148,  272,  201,  272,
      264,  264,  264,  264,  201,  148,  265,  265,  265,  265,
      272,  272,  269,  148,  272,  272,  272,  148,  272,   77,
      269,  272,  272,  272,  272,  148,  251,  272,  272,  272,
      201,   77,  264,  264,  264,  264,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  148,  272,  272,  272,  272,
      272,  272,  269,  272,  272,  272,  272,  148,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       60,  272,   60,   60,   60,   60,   60,   60,   60,   60,

       60,   83,  272,   83,   83,   83,   84,  272,   84,   84,
       84,   84,   86,   86,  272,   86,   86,   86,   86,  108,
      272,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      110,  272,  272,  272,  110,  110,  110,  110,  110,  110,
      110,  139,  272,  272,  139,  139,  160,  160,  160,  161,
      272,  161,  161,  161,  161,  180,  272,  272,  180,  180,
      180,  180,  180,  180,  180,  180,  195,  272,  272,  195,
      195,  197,  272,  272,  197,  197,  214,  272,  214,  214,
      214,  214,  230,  272,  272,  272,  230,  241,  272,  272,
      241,  241,  243,  272,  272,  243,  243,    7,  272,  272,

      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272
    } ;

static const flex_int16_t yy_chk[1258] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        5,   34,    5,    5,    6,   33,    6,    6,   21,   36,
       21,   21,   21,   21,   37,  267,   43,   38,   24,    4,
       24,   24,   24,   24,   40,   39,   44,   33,   41,  261,
       21,   42,    5,   24,   87,   34,    6,   46,   45,   47,

       24,   37,   36,   43,   92,   24,   88,   98,   39,   37,
       38,   38,   40,   44,   51,    5,   87,    5,   40,    6,
       39,    6,   23,   41,   23,   23,   23,   42,   45,   47,
       51,   46,   88,   89,   45,   23,   23,   23,  260,   23,
       23,   92,  259,   94,   23,   98,   23,  257,   23,   23,
       64,  100,   64,   64,   64,   64,   89,   23,   95,   90,
       65,   65,   65,   65,   23,   57,   66,   66,   66,   66,
       68,   68,   64,   67,   67,   67,   94,   57,   57,   57,
       65,   69,   69,   69,   71,   71,   71,   90,  103,  100,
       68,  270,   93,   67,   95,   57,  164,  171,   57,   57,

       69,  270,   57,   57,   71,  102,  104,  101,  173,   57,
      174,   57,   57,   57,   70,   57,   70,   57,   93,  105,
       70,   70,   70,   73,   73,   73,   74,  103,   74,   74,
       74,   74,  102,  164,   73,   73,  171,  174,   73,   73,
      101,   74,  173,   73,  104,   73,  266,   73,   74,  165,
      105,  256,  254,   74,  221,   75,   73,   75,   75,   75,
       75,  132,  132,   73,   76,  168,   76,   76,   76,   76,
       75,   85,  266,   85,   85,   85,   85,   75,  175,   76,
      165,  132,   75,  113,  113,  113,   76,  130,  130,  130,
      221,   76,   77,   85,   77,   77,  243,   77,   77,   77,

       77,   78,  168,   78,   78,   78,   78,  130,  242,  175,
       77,  241,  227,  131,  131,  131,   78,   77,  133,  133,
      216,  224,   77,   78,  129,  129,  129,  129,   78,  124,
      124,  124,  124,  131,  136,  136,  136,  129,  133,  124,
      124,  124,  124,  126,  129,  126,  126,  126,  126,  129,
      124,  124,  124,  124,  124,  124,  127,  216,  127,  127,
      127,  127,  223,  222,  128,  126,  128,  128,  128,  128,
      134,  134,  134,  134,  135,  135,  135,  166,  127,  137,
      137,  137,  137,  138,  138,  138,  128,  141,  141,  141,
      134,  142,  142,  135,  143,  143,  143,  176,  218,  137,

      144,  144,  144,  138,  166,  172,  217,  141,  166,  187,
      187,  142,  146,  143,  146,  146,  146,  146,  188,  188,
      144,  147,  220,  147,  147,  147,  147,  146,  215,  187,
      176,  189,  189,  172,  146,  219,  147,  225,  188,  146,
      217,  197,  148,  147,  148,  148,  148,  148,  147,  220,
      149,  189,  149,  149,  149,  149,  150,  148,  150,  150,
      150,  150,  226,  219,  148,  149,  179,  179,  179,  148,
      225,  150,  149,  184,  184,  184,  184,  149,  150,  196,
      195,  178,  151,  150,  151,  151,  151,  151,  152,  226,
      152,  152,  152,  152,  177,  170,  153,  151,  153,  153,

      153,  153,  169,  167,  151,  194,  194,  194,  194,  151,
      152,  154,  163,  154,  154,  154,  154,  155,  153,  155,
      155,  155,  155,  234,  234,  156,  154,  156,  156,  156,
      156,  162,  155,  154,  183,  183,  183,  183,  154,  155,
      156,  145,  140,  234,  155,  255,  157,  156,  157,  157,
      157,  157,  156,  139,  183,  125,  109,  107,  235,  235,
      182,  157,  182,  182,  182,  182,   99,   97,  157,  185,
      185,  185,  255,  157,  180,  180,  180,  180,  235,   96,
       91,   86,  182,   80,  180,  180,  180,  180,   79,  185,
      186,  186,  186,  258,   72,  180,  180,  180,  180,  180,

      180,  190,  190,  190,  190,  191,  191,  191,  191,   63,
      186,  192,  192,  192,  192,  193,  193,  193,  193,   56,
       53,  190,  198,  198,  198,  191,   49,  258,   35,   29,
       28,  192,   27,   26,  199,  193,  199,  199,  199,  199,
      236,  236,  198,  200,   17,  200,  200,  200,  200,  199,
       14,  232,  232,  232,  232,   10,  199,    7,  200,    3,
      236,  199,    2,    0,  201,  200,  201,  201,  201,  201,
      200,  232,  202,    0,  202,  202,  202,  202,  203,  201,
      203,  203,  203,  203,    0,    0,  201,  202,    0,    0,
        0,  201,    0,  203,  202,    0,    0,    0,    0,  202,

      203,    0,    0,    0,  204,  203,  204,  204,  204,  204,
      205,    0,  205,  205,  205,  205,    0,    0,  206,  204,
      206,  206,  206,  206,    0,  205,  204,    0,    0,    0,
        0,  204,  205,  206,    0,    0,    0,  205,    0,  207,
      206,  207,  207,  207,  207,  206,    0,  208,    0,  208,
      208,  208,  208,  209,  207,  209,  209,  209,  209,    0,
        0,  207,  208,    0,    0,    0,  207,    0,  209,  208,
        0,    0,    0,    0,  208,  209,    0,    0,    0,  210,
      209,  210,  210,  210,  210,  211,    0,  211,  211,  211,
      211,    0,    0,  212,  210,  212,  212,  212,  212,    0,

      211,  210,  237,  237,  237,  237,  210,  211,  212,    0,
        0,    0,  211,    0,  213,  212,  213,  213,  213,  213,
      212,  231,  237,  231,  231,  231,  231,    0,    0,  213,
        0,  233,  233,  233,  233,    0,  213,  238,  238,  238,
      238,  213,    0,  231,  233,  239,  239,  239,  239,    0,
        0,  233,  240,  240,  240,  240,  233,  238,  244,    0,
      244,  244,  244,  244,  245,  239,  245,  245,  245,  245,
        0,    0,  240,  244,    0,    0,    0,    0,    0,  245,
      244,    0,    0,    0,    0,  244,  245,    0,    0,    0,
      246,  245,  246,  246,  246,  246,  247,    0,  247,  247,

      247,  247,    0,    0,  248,  246,  248,  248,  248,  248,
        0,  247,  246,    0,    0,    0,    0,  246,  247,  248,
        0,    0,    0,  247,    0,  249,  248,  249,  249,  249,
      249,  248,    0,  250,    0,  250,  250,  250,  250,  251,
      249,  251,  251,  251,  251,    0,    0,  249,  250,    0,
        0,    0,  249,    0,  251,  250,    0,    0,    0,    0,
      250,  251,    0,    0,    0,  252,  251,  252,  252,  252,
      252,  253,    0,  253,  253,  253,  253,    0,    0,  262,
      252,  262,  262,  262,  262,    0,  253,  252,    0,    0,
        0,    0,  252,  253,  262,    0,    0,    0,  253,    0,

      263,  262,  263,  263,  263,  263,  262,    0,  264,    0,
      264,  264,  264,  264,  265,  263,  265,  265,  265,  265,
        0,    0,  263,  264,    0,    0,    0,  263,    0,  265,
      264,    0,    0,    0,    0,  264,  265,    0,    0,    0,
      269,  265,  269,  269,  269,  269,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  269,    0,    0,    0,    0,
        0,    0,  269,    0,    0,    0,    0,  269,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      275,    0,  275,  275,  275,  275,  275,  275,  275,  275,

      275,  276,    0,  276,  276,  276,  277,    0,  277,  277,
      277,  277,  278,  278,    0,  278,  278,  278,  278,  279,
        0,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      280,    0,    0,    0,  280,  280,  280,  280,  280,  280,
      280,  281,    0,    0,  281,  281,  282,  282,  282,  283,
        0,  283,  283,  283,  283,  284,    0,    0,  284,  284,
      284,  284,  284,  284,  284,  284,  285,    0,    0,  285,
      285,  286,    0,    0,  286,  286,  287,    0,  287,  287,
      287,  287,  288,    0,    0,    0,  288,  289,    0,    0,
      289,  289,  290,    0,    0,  290,  290,  272,  272,  272,

      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[92] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "RubyLexer.l"
#line 6 "RubyLexer.l"
	#include <stdio.h>
    #include "tree_nodes.h"
    #include "parser.tab.h"    

    void removeCharacterFromString(const char * str, char * dest, char deleted_char);
    int binstrToDec(const char * str);
#line 846 "lex.yy.c"

#line 848 "lex.yy.c"

#define INITIAL 0
#define ML_COMMENT 1
#define STRING 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 29 "RubyLexer.l"


   
#line 33 "RubyLexer.l"
    int num;
    float real_num;
    char temp1[100];
    char temp2[100];
    char comment[1000];
    char string[1000];
    int concatenation = 0;


#line 1084 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 273 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 272 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 42 "RubyLexer.l"
{ return AND; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 43 "RubyLexer.l"
{ return CLASS; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 44 "RubyLexer.l"
{ return DEF; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 45 "RubyLexer.l"
{ return DEFINED; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "RubyLexer.l"
{ return DO; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 47 "RubyLexer.l"
{ return IF; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 48 "RubyLexer.l"
{ return ELSE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 49 "RubyLexer.l"
{ return ELSIF; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 50 "RubyLexer.l"
{ return END; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 51 "RubyLexer.l"
{ return FALSE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 52 "RubyLexer.l"
{ return FOR; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 53 "RubyLexer.l"
{ return IN; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 54 "RubyLexer.l"
{ return NOT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 55 "RubyLexer.l"
{ return OR; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 56 "RubyLexer.l"
{ return RETURN; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 57 "RubyLexer.l"
{ return SELF; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 58 "RubyLexer.l"
{ return THEN; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 59 "RubyLexer.l"
{ return TRUE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 60 "RubyLexer.l"
{ return UNTIL; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 61 "RubyLexer.l"
{ return WHILE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 63 "RubyLexer.l"
{ return ARITHMETIC_PLUS_OP; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 64 "RubyLexer.l"
{ return ARITHMETIC_MINUS_OP; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 65 "RubyLexer.l"
{ return ARITHMETIC_MUL_OP; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 66 "RubyLexer.l"
{ return ARITHMETIC_DIV_OP; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 67 "RubyLexer.l"
{ return ARITHMETIC_MOD_OP; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 68 "RubyLexer.l"
{ return ARITHMETIC_POW_OP; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 70 "RubyLexer.l"
{ return EQL_OP; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 71 "RubyLexer.l"
{ return NOT_EQL_OP; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 72 "RubyLexer.l"
{ return GREATER_OP; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 73 "RubyLexer.l"
{ return LESS_OP; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 74 "RubyLexer.l"
{ return GREATER_OR_EQL_OP; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 75 "RubyLexer.l"
{ return LESS_OR_EQL_OP; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 76 "RubyLexer.l"
{ return COMB_COMPRASION_OP; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 77 "RubyLexer.l"
{ return CASE_EQL_OP; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 79 "RubyLexer.l"
{ return ASSIGN_OP; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 81 "RubyLexer.l"
{ return LOGICAL_AND_OP; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 82 "RubyLexer.l"
{ return LOGICAL_OR_OP; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 83 "RubyLexer.l"
{ return LOGICAL_NOT_OP; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 85 "RubyLexer.l"
{ return INCLUSIVE_RANGE_OP; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 86 "RubyLexer.l"
{ return EXCLUSIVE_RANGE_OP; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 88 "RubyLexer.l"
{ return DOT_SYMBOL; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 89 "RubyLexer.l"
{ return COMMA_SYMBOL; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 90 "RubyLexer.l"
{ return SEMICOLON_SYMBOL; }
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 91 "RubyLexer.l"
{ return NEW_LINE_SYMBOL;  }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 92 "RubyLexer.l"
{ return OPEN_ROUND_BRACKET; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 93 "RubyLexer.l"
{ return CLOSE_ROUND_BRACKET; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 94 "RubyLexer.l"
{ return OPEN_CURLY_BRACKET; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 95 "RubyLexer.l"
{
                if(concatenation == 0) {
                    return CLOSE_CURLY_BRACKET;
                } else {
                    concatenation--;
                    BEGIN(STRING);
                    string[0] = 0;
                    return ARITHMETIC_PLUS_OP;
                }
            }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 105 "RubyLexer.l"
{ return OPEN_SQUARE_BRACKET; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 106 "RubyLexer.l"
{ return CLOSE_SQUARE_BRACKET; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 108 "RubyLexer.l"
{ 
                string[0] = 0; 
                BEGIN(STRING);    
            }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 113 "RubyLexer.l"
{                         
                        concatenation++;
                        BEGIN(INITIAL);
                    }            
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 118 "RubyLexer.l"
{ strcat(string, yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 119 "RubyLexer.l"
{ strcat(string, yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 120 "RubyLexer.l"
{ strcat(string, "\n"); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 121 "RubyLexer.l"
{ strcat(string, "\a"); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 122 "RubyLexer.l"
{ strcat(string, "\b"); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 123 "RubyLexer.l"
{ strcat(string, "\t"); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 124 "RubyLexer.l"
{ strcat(string, "\v"); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 125 "RubyLexer.l"
{ strcat(string, "\f"); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 126 "RubyLexer.l"
{ strcat(string, "\r"); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 127 "RubyLexer.l"
{ strcat(string, "\e"); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 128 "RubyLexer.l"
{ strcat(string, " "); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 129 "RubyLexer.l"
{ strcat(string, "\\"); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 130 "RubyLexer.l"
{ strcat(string, "\""); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 131 "RubyLexer.l"
{ 
                                sscanf(yytext + 1, "%o", &num);
                                temp1[0] = (char) num;
                                temp1[1] = 0;
                                strcat(string, temp1);
                            }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 138 "RubyLexer.l"
{ 
                                sscanf(yytext + 2, "%x", &num);
                                temp1[0] = (char) num;
                                temp1[1] = 0;
                                strcat(string, temp1);
                            }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 144 "RubyLexer.l"
{ printf("ERROR: invalid hex escape \n"); } 
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 145 "RubyLexer.l"
{ printf("ERROR: expected \" \n");}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 146 "RubyLexer.l"
{ 
                yylval.string_un=(char *)malloc(strlen(string)+1);
                strcpy(yylval.string_un, string);
                BEGIN(INITIAL);
                return STRING;
            }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 153 "RubyLexer.l"
{ printf("Single-line comment: %s\n", yytext + 1); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 155 "RubyLexer.l"
{                                     
                            comment[0] = 0; 
                            BEGIN(ML_COMMENT);
                        }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 160 "RubyLexer.l"
{
                            strcat(comment, yytext + 5);
                            printf("Multi-line comment: %s\n", comment);
                            BEGIN(INITIAL);
                        }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 166 "RubyLexer.l"
{ 
                            strcat(comment, yytext); 
                        }
	YY_BREAK
case YY_STATE_EOF(ML_COMMENT):
#line 170 "RubyLexer.l"
{ 
                            printf("expected =end"); BEGIN(INITIAL); 
                        }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 174 "RubyLexer.l"
{ 
                                removeCharacterFromString(yytext,temp1,'_');
                                yylval.int_un = atoi(temp1);
                                return INTEGER_NUMBER;
                            }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 180 "RubyLexer.l"
{ printf("ERROR: invalid decimal number: %s\n", yytext); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 182 "RubyLexer.l"
{
                                removeCharacterFromString(yytext+2,temp1,'_');
                                yylval.int_un = atoi(temp1);
                                return INTEGER_NUMBER;              
                            }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 188 "RubyLexer.l"
{ printf("ERROR: invalid decimal number with dD: %s\n", yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 190 "RubyLexer.l"
{
                                removeCharacterFromString(yytext,temp1,'_');
                                removeCharacterFromString(temp1,temp2,'o');
                                removeCharacterFromString(temp2,temp1,'O');
                                yylval.int_un = num;
                                return INTEGER_NUMBER;
                            }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 198 "RubyLexer.l"
{ printf("ERROR: invalid octal number: %s\n", yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 200 "RubyLexer.l"
{
                                removeCharacterFromString(yytext + 2,temp1,'_');
                                yylval.int_un = num;
                                return INTEGER_NUMBER;
                            }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 206 "RubyLexer.l"
{ printf("ERROR: invalid hexadecimal number: %s\n", yytext); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 208 "RubyLexer.l"
{
                                removeCharacterFromString(yytext + 2,temp1,'_');
                                yylval.int_un = num;
                                return INTEGER_NUMBER; 
                            }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 214 "RubyLexer.l"
{ printf("ERROR: invalid binary number: %s\n", yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 217 "RubyLexer.l"
{
                                                                removeCharacterFromString(yytext,temp1,'_');                                                                  
                                                                real_num = (float) atof(temp1);
                                                                yylval.float_un = (float) real_num;
                                                                return FLOAT_NUMBER;
                                                            }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 223 "RubyLexer.l"
{ printf("ERROR: invalid float number: %s\n", yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 224 "RubyLexer.l"
{ printf("ERROR: invalid float number with eE: %s\n", yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 226 "RubyLexer.l"
{
                                                yylval.string_un=(char *)malloc(strlen(yytext)+1);
                                                strcpy(yylval.string_un, yytext); 
                                                return VAR_OR_METHOD_NAME;
                                            }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 232 "RubyLexer.l"
{
                                                yylval.string_un=(char *)malloc(strlen(yytext)+1);
                                                strcpy(yylval.string_un, yytext); 
                                                return INSTANCE_VAR_NAME;
                                            }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 238 "RubyLexer.l"
{
                                                yylval.string_un=(char *)malloc(strlen(yytext)+1);
                                                strcpy(yylval.string_un, yytext); 
                                                return CLASS_VAR_NAME;
                                            }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 244 "RubyLexer.l"
{
                                                yylval.string_un=(char *)malloc(strlen(yytext)+1);
                                                strcpy(yylval.string_un, yytext); 
                                                return CLASS_NAME;
                                            }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 250 "RubyLexer.l"
ECHO;
	YY_BREAK
#line 1696 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 273 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 273 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 272);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 250 "RubyLexer.l"


void removeCharacterFromString(const char * str, char * dest, char deleted_char) {
	int j = 0;
	
    for(int i = 0; str[i] != 0; i++) {
        if(str[i] != deleted_char) {
            dest[j++] = str[i];
        }
    }

    dest[j] = 0;
}

int binstrToDec(const char * str) {
    unsigned char *p = str;
    unsigned int   r = 0;

    while (p && *p ) {
        r <<= 1;
        r += (unsigned int)((*p++) & 0x01);
    }

    return (int) r;
}
