/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 131
#define YY_END_OF_BUFFER 132
static yyconst short int yy_acclist[486] =
    {   0,
      113,  113,  132,  131,   70,  131,   83,  131,  110,  131,
       43,  131,   62,  131,   77,  131,   78,  131,   41,  131,
       39,  131,   76,  131,   40,  131,   75,  131,   42,  131,
      114,  124,  125,  131,  114,  115,  124,  125,  131,   74,
      131,   48,  131,   55,  131,   47,  131,  131,  131,  130,
      131,  130,  131,  126,  130,  131,   81,  131,   82,  131,
       64,  131,  127,  131,  127,  131,  127,  131,  127,  131,
      127,  131,  126,  127,  131,  127,  131,  127,  131,  127,
      131,  127,  131,  127,  131,  127,  131,  127,  131,  127,
      131,  127,  131,  127,  131,  127,  131,  127,  131,   79,

      131,   63,  131,   80,  131,   65,  131,   55,  131,  113,
      131,  113,  131,   85,  131,  109,  131,   85,  131,  131,
       46,  110,   60,   68,   44,   58,   56,   57,   72,  125,
       59,  125,  118,  119,  125,  118,  119,  125,  125,  126,
      125,  114,  115,  124,  125,  114,  115,  124,  125,  115,
      125,   66,   50,   45,   49,   67,   71,  128,  130,  130,
      126,  126,  130,  126,  130,  130,  126,  130,  125,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,   10,
      127,  126,  127,  126,  127,  126,  127,  127,  127,  127,
      127,  127,   18,  127,   19,  127,  127,  127,  127,  127,

       24,  127,  127,  127,  127,  127,  127,  127,  127,  127,
       69,  113,  113,   85,   84,   85,   96,  106,   95,   87,
       88,   93,   91,   86,   92,   94,   89,   90,  108,   61,
       73,  125,  125,  126,  125,  124,  125,  118,  119,  125,
      118,  119,  125,  119,  125,  122,  123,  116,  117,  126,
      124,  126,  118,  119,  120,  121,  119,  125,  114,  115,
      124,  125,  115,  125,   51,   52,  129,  128,  130,   13,
      130,  125,  127,  125,  127,  125,  127,  127,    2,  127,
      127,  127,  127,  127,    8,  127,  127,   14,  127,  127,
      127,  127,  127,   17,  127,  127,  127,   22,  127,   23,

      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  113,  106,  104,   98,  108,  107,
      125,  124,  125,  125,  118,  119,  125,  119,  125,  122,
      123,  123,  123,  116,  117,  117,  117,  124,  124,  126,
      126,  118,  119,  119,  119,  120,  121,  121,  121,  119,
      125,  119,  125,  114,  115,  124,  125,  115,  125,  129,
      130,  127,  127,  127,    6,  127,  127,  127,   11,  127,
      127,  127,   53,  127,  127,  127,   21,  127,   25,  127,
      127,  127,  127,   29,  127,  127,   31,  127,   32,  127,
      127,  127,  127,   36,  127,  127,  127,  112,  113,  106,

      105,   99,  100,   97,  107,  124,  125,  118,  119,  125,
      122,  123,  123,  123,  116,  117,  117,  117,  124,  124,
      126,  118,  119,  119,  119,  120,  121,  121,  121,  115,
      125,    3,  130,    1,  127,    4,  127,    5,  127,    7,
      127,  127,   12,  127,  127,  127,   16,  127,  127,  127,
       27,  127,  127,   30,  127,   33,  127,  127,   35,  127,
       37,  127,   38,  127,  124,  125,  124,  127,   15,  127,
       54,   20,  127,   26,  127,   28,  127,   34,  127,  111,
      102,  103,  127,  101,    9
    } ;

static yyconst short int yy_accept[364] =
    {   0,
        1,    1,    1,    2,    3,    3,    3,    4,    5,    7,
        9,   11,   13,   15,   17,   19,   21,   23,   25,   27,
       29,   31,   35,   40,   42,   44,   46,   48,   49,   50,
       52,   54,   57,   59,   61,   63,   65,   67,   69,   71,
       73,   76,   78,   80,   82,   84,   86,   88,   90,   92,
       94,   96,   98,  100,  102,  104,  106,  108,  110,  112,
      114,  116,  118,  120,  121,  122,  123,  124,  125,  126,
      127,  128,  129,  130,  131,  131,  132,  133,  136,  139,
      140,  140,  140,  141,  141,  141,  142,  146,  150,  152,
      153,  154,  155,  156,  157,  158,  158,  159,  160,  161,

      162,  164,  166,  167,  169,  171,  172,  173,  174,  175,
      176,  177,  178,  179,  180,  182,  184,  186,  188,  189,
      190,  191,  192,  193,  195,  197,  198,  199,  200,  201,
      203,  204,  205,  206,  207,  208,  209,  210,  211,  212,
      212,  213,  214,  215,  217,  218,  219,  219,  219,  220,
      221,  222,  222,  223,  224,  225,  226,  227,  228,  229,
      230,  231,  232,  233,  234,  235,  236,  238,  241,  244,
      246,  248,  248,  250,  250,  250,  251,  253,  255,  255,
      257,  257,  259,  259,  259,  259,  259,  263,  265,  266,
      267,  268,  269,  270,  272,  274,  276,  278,  279,  281,

      282,  283,  284,  285,  287,  288,  290,  291,  292,  293,
      294,  296,  297,  298,  300,  302,  303,  304,  305,  306,
      307,  308,  309,  310,  311,  312,  313,  314,  315,  315,
      316,  317,  317,  317,  318,  318,  319,  319,  320,  321,
      322,  324,  325,  328,  330,  332,  333,  334,  336,  337,
      338,  339,  341,  342,  344,  345,  346,  348,  349,  350,
      352,  354,  358,  360,  361,  362,  363,  364,  365,  367,
      368,  369,  371,  372,  373,  374,  375,  376,  377,  379,
      381,  382,  383,  384,  386,  387,  389,  391,  392,  393,
      394,  396,  397,  398,  398,  400,  401,  402,  403,  403,

      404,  404,  405,  406,  408,  411,  413,  414,  415,  417,
      418,  419,  420,  420,  422,  424,  425,  426,  428,  429,
      430,  432,  434,  436,  438,  440,  442,  443,  445,  446,
      447,  449,  450,  451,  453,  454,  456,  458,  459,  461,
      463,  465,  465,  465,  465,  465,  467,  468,  469,  471,
      472,  474,  476,  478,  480,  481,  481,  482,  483,  484,
      485,  486,  486
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   19,   19,   20,    1,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   26,
       31,   32,   33,   32,   32,   32,   34,   35,   36,   32,
       32,   32,   32,   32,   32,   32,   32,   37,   32,   32,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
       67,   52,   68,   69,   70,   71,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[72] =
    {   0,
        1,    2,    1,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    4,    1,    5,    5,    5,    5,    1,
        1,    1,    1,    1,    6,    5,    5,    5,    5,    5,
        7,    7,    7,    7,    7,    7,    7,    1,    8,    1,
        1,    9,   10,   10,   10,   10,   10,   10,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,    1,    1,
        1
    } ;

static yyconst short int yy_base[381] =
    {   0,
        0, 1084, 1103,   70,   71,   75, 1104, 1121, 1077, 1121,
        0, 1075, 1086, 1121, 1121,   64, 1070, 1121, 1069,   71,
     1065,  101,   79, 1121,   60, 1064,   61, 1065, 1050,    0,
     1044,  135, 1121, 1121, 1121,   85,   80,   64,   86,  109,
      169,   98, 1055,   77,   93,  121,  102,   92,  128,  130,
      108,  143,  118, 1121,  998, 1121, 1121,  137,    0, 1013,
        0, 1121,  991,  225, 1121,    0, 1121, 1121, 1036, 1121,
     1121, 1121,  178,  184,  190, 1121,  219,  232,  276,  282,
      202,  238,  291,  297, 1011,  326,  318,  357,  340, 1121,
     1025, 1025, 1121, 1121, 1121,    0,    0,    0, 1005,  372,

      175,  996, 1000,  228,  379, 1009,  389,  162,  175,  198,
      132,  210,  240,  263, 1007,  364,  263,  380,  264,  270,
      213,  274,  157, 1002, 1001,  220,   94,  312,  268,  990,
      355,  313,  283,  332,  289,  386,  333,  388, 1121,  931,
        0,  921,    0,    0, 1121,  333,  963,  962, 1121, 1121,
     1121,  389, 1121, 1121,  917, 1121, 1121, 1121, 1121,  440,
     1121,  433,  460,  475,  481,  490,  496,  517,  523,  502,
      223,  421,  532,  454,  424,  538,  544,  550,  555,  930,
      929,  565,  448,  558,  571,  928,  585,  592, 1121, 1121,
        0,    0,  936,    0,  600,  606,  621,  401,  953,  201,

      410,  398,  364,  371,  582,  952,  367,  149,  419,  440,
      951,  466,  468,  950,  949,  446,  576,  531,  612,  584,
      363,  614,  627,  629,  630,  513,  591,  632,  912,  914,
      633,  628,  616, 1121,  925, 1121,  896,  679,    0,  648,
      698,  661,  716,  725,  641,  668,  671,  731,  735,  743,
      752,  762,  770,  748,  775,  779,  903,  902,  901,  784,
      792,  811,  819,    0,  905,  532,  645,  640,  925,  657,
      655,  923,  654,  170, 1121,  675,  690,  677,  922,  921,
      656,  511,  678,  919,  722,  918,  917,  707,  659,  761,
      873,  758,  415,  834,    0, 1121, 1121, 1121,  729, 1121,

      866, 1121, 1121,  826,  846,  830,  835,  838,  865,  873,
      878,  882,  886,  892,  896,  900,  905,  836,  833,  832,
      911,    0,  857,  856,  834,  805,  769,  793,  785,  799,
      742,  810,  872,  686,  912,  685,  658,  806,  642,  571,
      510,  425,  433,  298,  295,  932,  938,  804,  306, 1121,
      246,  231,  160,  147, 1121,   39, 1121, 1121,  845, 1121,
     1121, 1121,  980,  991, 1002, 1008, 1015, 1023, 1034, 1045,
     1052, 1054, 1061, 1072, 1079, 1085, 1091, 1098, 1104, 1110
    } ;

static yyconst short int yy_def[381] =
    {   0,
      362,    1,  363,  363,  364,  364,  362,  362,  362,  362,
      365,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  366,  367,
      367,  367,  362,  362,  362,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  362,  362,  362,  362,  362,  369,  369,
      370,  362,  370,  362,  362,  365,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  371,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  372,  373,  367,  367,  362,

       32,   32,  367,   32,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,   41,   41,   41,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  362,  362,
      369,  369,  370,  370,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  374,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  375,
      376,  362,  362,  362,  362,  376,  362,  362,  362,  362,
      377,  373,  367,  367,  368,  368,  368,  368,  368,  368,

      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  362,  369,
      362,  362,  362,  362,  362,  362,  362,  374,  378,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  375,  379,  380,  362,
      362,  362,  362,  377,  367,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  362,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  362,  369,  362,  362,  362,  362,  362,

      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  379,  380,  380,
      362,  367,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  362,  362,  362,  362,  362,  362,  368,  368,  362,
      368,  368,  368,  368,  362,  362,  362,  362,  368,  362,
      362,    0,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362
    } ;

static yyconst short int yy_nxt[1193] =
    {   0,
        8,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   23,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   30,   30,   32,
       30,   30,   30,   30,   30,   30,   30,   33,    8,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   43,
       44,   43,   43,   43,   45,   46,   47,   43,   43,   48,
       49,   50,   51,   43,   52,   43,   53,   54,   55,   56,
       57,    8,    8,   69,   62,   63,    8,  362,   62,   63,
       90,   91,   93,   94,   73,   70,   74,   74,   74,   74,
      362,   60,   77,  362,   87,   88,   88,   88,   75,  362,

      105,  105,  105,  105,  360,  362,  362,  362,   83,   64,
      110,  362,   75,   64,   77,  362,   78,   79,   79,   80,
       89,  362,  362,  111,  124,   83,  107,   81,  112,   82,
       83,  362,  125,  108,  362,  109,   84,   85,  131,  113,
      122,  362,   86,  362,   81,  362,   82,   83,  100,  126,
      101,  101,  101,  101,  123,  114,  362,   84,   92,  213,
      362,  130,  362,  136,  102,  115,   85,  127,  138,  103,
      362,  128,  275,  362,  132,  362,  104,  129,  201,  134,
      140,  102,  100,  362,  116,  116,  116,  116,  362,  135,
      133,  162,  137,   74,   74,   74,   74,  163,  117,  164,

       80,   80,   80,   75,   98,   74,   74,   74,   74,   98,
      118,  362,  198,  165,  362,  117,  211,  171,  171,   75,
      199,   98,  119,  362,  120,  163,  362,  121,  145,  329,
      165,   75,  166,  362,  167,  167,  167,  167,  245,  245,
      146,  146,  146,  172,  362,  163,  200,  168,  169,  169,
       80,  267,  147,  362,  173,  173,  173,   98,  148,  362,
      163,  165,   98,  149,  246,  212,  208,  150,  151,  152,
      202,  153,  154,  170,   98,  209,  362,  362,  165,  174,
      155,  362,  203,  362,  156,  157,  158,  362,  159,  163,
      160,  168,  169,  169,   80,  163,  362,  164,   80,   80,

       80,  175,  362,  175,  100,  165,  176,  177,  177,  177,
      204,  165,  178,  178,  178,  206,  106,  170,  106,  362,
      165,  106,  165,  163,  205,  362,  362,  210,  165,  215,
      207,   77,  100,   87,   88,   88,   88,  165,  179,  163,
      220,  182,  182,  182,  164,  362,  362,   83,  231,  231,
      231,  222,  183,  163,  184,  187,  187,  187,  187,   89,
      358,  185,  186,  357,   83,  214,  219,   86,  362,  183,
       77,  184,   87,   88,   88,   88,  362,  362,  221,  226,
      362,  188,  185,  227,  362,  100,   83,  176,  176,  176,
      176,  186,  163,  106,  195,  196,  196,  196,   89,  362,

      216,  362,   75,   83,  105,  105,  105,  105,  117,  106,
      106,  362,  234,  100,  362,  217,  218,  106,  286,  106,
      197,  271,  106,  362,  270,  117,  106,  235,  362,  274,
      107,  223,  362,  106,  228,  106,  247,  247,  106,  224,
      251,  251,  251,  266,  269,  356,   75,  225,   74,   74,
       74,   74,  268,  362,  236,  239,  239,  239,  239,  362,
      341,  276,  172,  247,  247,  239,  239,  239,  239,  239,
      250,  250,  250,  163,   75,  164,  164,  164,  164,  362,
      355,  362,  239,  239,  239,  239,  239,  239,  163,  172,
      164,   80,   80,   80,  100,  174,  176,  176,  176,  176,

      277,  163,  280,  240,  165,  167,  167,  167,  167,  163,
      165,  167,  241,  241,  241,  163,  163,  243,  243,  243,
      164,  165,  100,  362,  362,   83,  362,  165,  278,  279,
      163,  163,  168,  169,  169,   80,  163,  242,  168,  169,
      169,   80,   83,  244,  362,  362,  165,  248,  248,  248,
      248,  100,  165,  176,  176,  176,  176,  100,  170,  252,
      252,  252,  252,  165,  170,  254,  254,  254,  291,  165,
      256,  256,  256,  249,  250,  250,  250,  334,  163,  100,
      260,  261,  261,   80,  362,  253,  256,  256,  256,  362,
      282,  255,  323,  283,  165,  362,  179,  362,   77,  174,

      187,  262,  262,  262,  362,  163,  244,  263,  263,  263,
      263,  165,  179,  163,   83,  195,  196,  196,  196,  163,
      281,  195,  196,  196,  196,  362,   89,  362,  272,  117,
      285,   83,  273,  188,  163,  117,  195,  195,  195,  195,
      362,  197,  362,  362,  292,  362,  117,  197,  296,  296,
      296,  297,  117,  362,  299,  362,  245,  245,  362,  284,
      287,  163,  197,  167,  167,  167,  167,  362,  362,  362,
      362,  362,  362,  288,  163,  289,  304,  304,  304,  304,
      290,  300,  246,  306,  306,  293,  308,  308,  362,  163,
      362,  362,  325,  298,  362,  362,  362,  362,  362,  362,

      324,  328,  163,  362,  362,  362,  362,  362,  362,  307,
      327,  163,  307,  167,  241,  241,  241,  326,  333,  338,
      362,  362,  362,  362,  362,  362,  362,   83,  330,  163,
      332,  243,  305,  305,   80,  362,  331,  335,  163,  242,
      260,  260,  260,  164,   83,  165,  248,  248,  248,  248,
      309,  309,  309,  309,  337,  362,  343,  170,  311,  311,
      311,  311,  165,  254,  254,  254,  244,  312,  312,  312,
      312,  362,  249,  344,  362,  100,  310,  252,  252,  252,
      252,  336,  362,  100,  310,  314,  314,  314,  314,  255,
      315,  315,  315,  313,  317,  317,  317,  163,  362,  260,

      261,  261,   80,  253,  340,  163,  362,  260,  261,  261,
       80,  100,  362,  165,  339,  348,  316,  362,  362,  362,
      316,  165,  350,  362,   77,  244,  187,  262,  262,  262,
      165,  349,  163,  244,  263,  321,  321,  321,  165,  163,
       83,  304,  346,  346,  346,  306,  306,  362,  165,  359,
      308,  308,   89,  308,  308,   83,  351,   83,  362,  163,
      188,  243,  305,  305,   80,  165,  354,  242,  361,  362,
      362,  246,   83,  319,  319,  165,  307,  258,  345,  307,
      309,  309,  309,  309,  342,  362,  362,  170,  311,  311,
      311,  311,  165,  311,  311,  311,  311,  312,  312,  312,

      312,  347,  347,  347,  347,  100,  249,  314,  314,  314,
      314,  315,  315,  315,  310,  317,  317,  317,  352,  310,
      317,  317,  317,  313,  163,  362,  263,  321,  321,  321,
      362,  362,  362,  253,  362,  362,  362,  255,  362,  322,
      165,  316,  319,  319,  258,  163,  316,  304,  346,  346,
      346,  302,  188,  347,  347,  347,  347,  165,  301,  295,
      294,   83,  362,  362,  362,  362,  362,  353,  265,  181,
      181,  258,  237,  242,  233,  232,  230,  229,   83,  313,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   61,   61,   61,   61,   61,   61,   61,   61,   61,

       61,   61,   66,  362,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   97,  362,  362,   97,   97,   97,   98,
      362,   98,  362,   98,   98,   98,  106,  106,  194,  106,
       98,  106,  106,  106,  141,  193,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  143,  190,  189,  143,  143,
      143,  143,  181,  143,  143,  143,  180,  161,  144,  142,
      180,  180,  191,  191,  191,  192,  139,  192,  362,  192,
      192,  192,  238,   99,   96,  238,  238,  238,  238,  238,
      238,  238,  238,  257,   95,   92,   76,  257,  257,  259,
       72,   71,   68,  259,  259,  264,   67,  264,   65,  264,

      264,  264,  303,  362,    8,   58,  362,  303,  318,  362,
      362,  362,  318,  318,  320,  362,  362,  362,  320,  320,
        7,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362

    } ;

static yyconst short int yy_chk[1193] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,   16,    5,    5,    6,   38,    6,    6,
       25,   25,   27,   27,   20,   16,   20,   20,   20,   20,
       44,    4,   23,   37,   23,   23,   23,   23,   36,   39,

       36,   36,   36,   36,  356,   48,   45,  127,   23,    5,
       38,   42,   20,    6,   22,   47,   22,   22,   22,   22,
       23,   51,   40,   38,   44,   23,   36,   22,   39,   22,
       22,   53,   44,   37,   46,   37,   22,   22,   48,   39,
       42,   49,   22,   50,   22,  111,   22,   22,   32,   45,
       32,   32,   32,   32,   42,   40,   52,   22,   58,  127,
      354,   47,  208,   51,   32,   40,   22,   46,   53,   32,
      123,   46,  208,  353,   49,  108,   32,   46,  111,   50,
       58,   32,   41,  274,   41,   41,   41,   41,  109,   50,
       49,   73,   52,   73,   73,   73,   73,   74,   41,   74,

       74,   74,   74,   75,  101,   75,   75,   75,   75,  101,
       41,  110,  108,   74,  200,   41,  123,   81,   81,   73,
      109,  101,   41,  112,   41,   74,  121,   41,   64,  274,
       74,   75,   77,  126,   77,   77,   77,   77,  171,  171,
       64,   64,   64,   81,  352,   78,  110,   78,   78,   78,
       78,  200,   64,  113,   82,   82,   82,  104,   64,  351,
       77,   78,  104,   64,  171,  126,  121,   64,   64,   64,
      112,   64,   64,   78,  104,  121,  114,  119,   78,   82,
       64,  129,  113,  120,   64,   64,   64,  122,   64,   79,
       64,   79,   79,   79,   79,   80,  133,   80,   80,   80,

       80,   83,  135,   83,   83,   79,   83,   83,   83,   83,
      114,   80,   84,   84,   84,  120,  117,   79,  117,  349,
       83,  117,   79,   80,  119,  128,  132,  122,   80,  129,
      120,   87,   83,   87,   87,   87,   87,   83,   84,   86,
      133,   86,   86,   86,   86,  134,  137,   87,  146,  146,
      146,  135,   86,   89,   86,   89,   89,   89,   89,   87,
      345,   86,   86,  344,   87,  128,  132,   86,  131,   86,
       88,   86,   88,   88,   88,   88,  221,  203,  134,  137,
      207,   89,   86,  137,  204,  100,   88,  100,  100,  100,
      100,   86,  105,  116,  105,  105,  105,  105,   88,  136,

      131,  138,  107,   88,  107,  107,  107,  107,  105,  118,
      116,  202,  152,  100,  198,  131,  131,  116,  221,  116,
      105,  204,  116,  201,  203,  105,  118,  152,  293,  207,
      107,  136,  209,  118,  138,  118,  172,  172,  118,  136,
      175,  175,  175,  198,  202,  343,  162,  136,  162,  162,
      162,  162,  201,  210,  152,  160,  160,  160,  160,  216,
      293,  209,  172,  183,  183,  160,  160,  160,  160,  160,
      174,  174,  174,  163,  162,  163,  163,  163,  163,  212,
      342,  213,  160,  160,  160,  160,  160,  160,  164,  183,
      164,  164,  164,  164,  165,  174,  165,  165,  165,  165,

      210,  163,  216,  166,  164,  166,  166,  166,  166,  167,
      165,  167,  167,  167,  167,  170,  164,  170,  170,  170,
      170,  164,  165,  341,  282,  167,  226,  165,  212,  213,
      168,  166,  168,  168,  168,  168,  169,  167,  169,  169,
      169,  169,  167,  170,  218,  266,  168,  173,  173,  173,
      173,  176,  169,  176,  176,  176,  176,  177,  168,  177,
      177,  177,  177,  168,  169,  178,  178,  178,  226,  169,
      179,  179,  179,  173,  184,  184,  184,  282,  182,  176,
      182,  182,  182,  182,  340,  177,  185,  185,  185,  217,
      218,  178,  266,  218,  182,  205,  179,  220,  187,  184,

      187,  187,  187,  187,  227,  188,  182,  188,  188,  188,
      188,  182,  185,  195,  187,  195,  195,  195,  195,  196,
      217,  196,  196,  196,  196,  219,  187,  222,  205,  195,
      220,  187,  205,  188,  197,  196,  197,  197,  197,  197,
      223,  195,  224,  225,  227,  228,  195,  196,  231,  231,
      231,  232,  196,  268,  233,  339,  245,  245,  267,  219,
      222,  240,  197,  240,  240,  240,  240,  273,  271,  281,
      270,  337,  289,  223,  242,  224,  242,  242,  242,  242,
      225,  233,  245,  246,  246,  228,  247,  247,  276,  240,
      278,  283,  268,  232,  238,  238,  238,  238,  336,  334,

      267,  273,  242,  277,  238,  238,  238,  238,  238,  246,
      271,  241,  247,  241,  241,  241,  241,  270,  281,  289,
      288,  238,  238,  238,  238,  238,  238,  241,  276,  243,
      278,  243,  243,  243,  243,  285,  277,  283,  244,  241,
      244,  244,  244,  244,  241,  243,  248,  248,  248,  248,
      249,  249,  249,  249,  288,  331,  299,  243,  250,  250,
      250,  250,  243,  254,  254,  254,  244,  251,  251,  251,
      251,  292,  248,  299,  290,  252,  249,  252,  252,  252,
      252,  285,  327,  253,  250,  253,  253,  253,  253,  254,
      255,  255,  255,  251,  256,  256,  256,  260,  329,  260,

      260,  260,  260,  252,  292,  261,  328,  261,  261,  261,
      261,  253,  330,  260,  290,  327,  255,  348,  326,  338,
      256,  261,  330,  332,  262,  260,  262,  262,  262,  262,
      260,  329,  263,  261,  263,  263,  263,  263,  261,  304,
      262,  304,  304,  304,  304,  306,  306,  325,  263,  348,
      307,  307,  262,  308,  308,  304,  332,  262,  359,  305,
      263,  305,  305,  305,  305,  263,  338,  304,  359,  324,
      323,  306,  304,  320,  319,  305,  307,  318,  301,  308,
      309,  309,  309,  309,  294,  333,  291,  305,  310,  310,
      310,  310,  305,  311,  311,  311,  311,  312,  312,  312,

      312,  313,  313,  313,  313,  314,  309,  314,  314,  314,
      314,  315,  315,  315,  310,  316,  316,  316,  333,  311,
      317,  317,  317,  312,  321,  335,  321,  321,  321,  321,
      287,  286,  284,  314,  280,  279,  272,  315,  269,  265,
      321,  316,  259,  258,  257,  346,  317,  346,  346,  346,
      346,  237,  321,  347,  347,  347,  347,  321,  235,  230,
      229,  346,  215,  214,  211,  206,  199,  335,  193,  186,
      181,  180,  155,  346,  148,  147,  142,  140,  346,  347,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  364,  364,  364,  364,  364,  364,  364,  364,  364,

      364,  364,  365,  130,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  366,  125,  124,  366,  366,  366,  367,
      115,  367,  106,  367,  367,  367,  368,  368,  103,  368,
      102,  368,  368,  368,  369,   99,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  370,   92,   91,  370,  370,
      370,  370,   85,  370,  370,  370,  371,   69,   63,   60,
      371,  371,  372,  372,  372,  373,   55,  373,   43,  373,
      373,  373,  374,   31,   29,  374,  374,  374,  374,  374,
      374,  374,  374,  375,   28,   26,   21,  375,  375,  376,
       19,   17,   13,  376,  376,  377,   12,  377,    9,  377,

      377,  377,  378,    7,    3,    2,    0,  378,  379,    0,
        0,    0,  379,  379,  380,    0,    0,    0,  380,  380,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362

    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
#define INITIAL 0
#define YY_NEVER_INTERACTIVE 1
#line 6 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
	#include <stdio.h>    

    void removeCharacterFromString(const char * str, char * dest, char deleted_char);
    int binstrToDec(const char * str);
#define ML_COMMENT 1

#define STRING 2

#line 828 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 27 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"


   
    int num;
    float real_num;
    char temp1[100];
    char temp2[100];
    char comment[1000];
    char string[1000];
    int concatenation = 0;


#line 995 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 363 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1121 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 39 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: alias\n"); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 40 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: and\n"); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 41 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: BEGIN\n"); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 42 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: begin\n"); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 43 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: break\n"); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 44 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: case\n"); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 45 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: class\n"); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 46 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: def\n"); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 47 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: defined?\n"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 48 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: do\n"); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 49 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: else\n"); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 50 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: elsif\n"); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 51 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: END\n"); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 52 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: end\n"); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 53 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: ensure\n"); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 54 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: false\n"); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 55 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: for\n"); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 56 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: if\n"); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 57 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: in\n"); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 58 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: module\n"); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 59 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: next\n"); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 60 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: nil\n"); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 61 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: not\n"); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 62 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: or\n"); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 63 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: redo\n"); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 64 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: rescue\n"); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 65 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: retry\n"); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 66 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: return\n"); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 67 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: self\n"); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 68 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: super\n"); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 69 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: then\n"); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 70 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: true\n"); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 71 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: undef\n"); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 72 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: unless\n"); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 73 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: until\n"); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 74 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: when\n"); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 75 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: while\n"); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 76 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Keyword: yield\n"); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 78 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: +\n"); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 79 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: -\n"); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 80 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: *\n"); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 81 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: /\n"); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 82 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: %\n"); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 83 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: **\n"); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 85 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: ==\n"); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 86 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: !=\n"); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 87 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: >\n"); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 88 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: <\n"); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 89 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: >=\n"); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 90 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: <=\n"); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 91 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: <=>\n"); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 92 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: ===\n"); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 93 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: eql?\n"); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 94 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: equal?\n"); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 96 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: =\n"); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 97 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: +=\n"); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 98 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: -=\n"); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 99 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: *=\n"); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 100 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: /=\n"); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 101 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: %=\n"); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 102 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: **=\n"); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 104 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: &\n"); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 105 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: |\n"); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 106 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: ^\n"); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 107 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: ~\n"); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 108 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: <<\n"); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 109 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: >>\n"); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 111 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: &&\n"); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 112 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: ||\n"); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 113 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: !\n"); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 115 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: ?:\n"); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 117 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: ..\n"); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 118 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Operator: ...\n"); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 120 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Sign: :\n"); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 121 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Sign: .\n"); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 122 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Sign: ,\n"); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 123 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Bracket: (\n"); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 124 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Bracket: )\n"); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 125 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Bracket: {\n"); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 126 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{
                if(concatenation == 0) {
                    printf("Bracket: }\n");
                } else {
                    concatenation--;
                    BEGIN(STRING);
                    string[0] = 0;
                    printf("Found СЃoncatenation with string\n");
                }
            }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 136 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Bracket: [\n"); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 137 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Bracket: ]\n"); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 139 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ 
                string[0] = 0; 
                BEGIN(STRING);    
            }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 144 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ 
                        printf("String: %s\n", string);
                        printf("Found СЃoncatenation with string\n");
                        concatenation++;
                        BEGIN(INITIAL);
                    }            
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 151 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ strcat(string, yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 152 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ strcat(string, "\n"); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 153 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ strcat(string, "\a"); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 154 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ strcat(string, "\b"); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 155 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ strcat(string, "\t"); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 156 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ strcat(string, "\v"); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 157 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ strcat(string, "\f"); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 158 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ strcat(string, "\r"); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 159 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ strcat(string, "\e"); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 160 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ strcat(string, " "); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 161 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ strcat(string, "\\"); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 162 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ strcat(string, "\""); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 163 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ strcat(string, "\nnn"); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 164 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ strcat(string, "\cx"); }  
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 165 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ strcat(string, "\C-x"); }  
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 166 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ strcat(string, "\M-x"); }  
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 167 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ strcat(string, "\M-\C-x"); }  
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 168 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ strcat(string, "\M-\cx"); }  
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 169 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ strcat(string, "\c\M-x"); }  
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 170 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ strcat(string, "\c?"); }  
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 171 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ strcat(string, "\C-?"); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 172 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ 
                                sscanf(yytext + 1, "%o", &num);
                                temp1[0] = (char) num;
                                temp1[1] = 0;
                                strcat(string, temp1);
                            }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 179 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ 
                                sscanf(yytext + 2, "%x", &num);
                                temp1[0] = (char) num;
                                temp1[1] = 0;
                                strcat(string, temp1);
                            }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 185 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("ERROR: invalid hex escape \n"); } 
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 186 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("ERROR: expected \" \n");}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 187 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("String: %s \n", string); BEGIN(INITIAL); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 189 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("Single-line comment: %s\n", yytext + 1); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 191 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{                                     
                            comment[0] = 0; 
                            BEGIN(ML_COMMENT);
                        }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 196 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{
                            strcat(comment, yytext + 5);
                            printf("Multi-line comment: %s\n", comment);
                            BEGIN(INITIAL);
                        }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 202 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ 
                            strcat(comment, yytext); 
                        }
	YY_BREAK
case YY_STATE_EOF(ML_COMMENT):
#line 206 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ 
                            printf("expected =end"); BEGIN(INITIAL); 
                        }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 210 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ 
                                removeCharacterFromString(yytext,temp1,'_');
                                num = atoi(temp1);
                                printf("Decimal number: %d\n", num);
                            }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 216 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("ERROR: invalid decimal number: %s\n", yytext); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 218 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{
                                removeCharacterFromString(yytext+2,temp1,'_');
                                num = atoi(temp1);
                                printf("Decimal number: %d\n", num);              
                            }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 224 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("ERROR: invalid decimal number with dD: %s\n", yytext); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 226 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{
                                removeCharacterFromString(yytext,temp1,'_');
                                removeCharacterFromString(temp1,temp2,'o');
                                removeCharacterFromString(temp2,temp1,'O');
                                sscanf(temp1,"%o",&num);
                                printf("Octal number: %d\n", num);
                            }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 234 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("ERROR: invalid octal number: %s\n", yytext); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 236 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{
                                removeCharacterFromString(yytext + 2,temp1,'_');
                                sscanf(temp1,"%x",&num);
                                printf("Hexadecimal number: %d\n", num);
                            }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 242 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("ERROR: invalid hexadecimal number: %s\n", yytext); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 244 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{
                                removeCharacterFromString(yytext + 2,temp1,'_');
                                num = binstrToDec(temp1);
                                printf("Binary number: %d\n", num); 
                            }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 250 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("ERROR: invalid binary number: %s\n", yytext); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 253 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{
                                                                 removeCharacterFromString(yytext,temp1,'_');                                                                 
                                                                 printf("Float number: %f\n", temp1); 
                                                            }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 258 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("ERROR: invalid float number: %s\n", yytext); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 260 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{ printf("ERROR: invalid float number with eE: %s\n", yytext); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 262 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{
                                                printf("Local variable or method name: %s\n", yytext);
                                            }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 266 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{
                                                printf("Instance variable: %s\n", yytext);
                                            }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 270 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{
                                                printf("Class variable: %s\n", yytext);
                                            }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 274 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
{
                                                printf("Class name: %s\n", yytext);
                                            }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 278 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"
ECHO;
	YY_BREAK
#line 1821 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 363 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 363 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 362);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 278 "C:\\Users\\black\\OneDrive\\Рабочий стол\\RubyCompiler\\RubyLexer.l"


void removeCharacterFromString(const char * str, char * dest, char deleted_char) {
	int j = 0;
	
    for(int i = 0; str[i] != 0; i++) {
        if(str[i] != deleted_char) {
            dest[j++] = str[i];
        }
    }

    dest[j] = 0;
}

int binstrToDec(const char * str) {
    unsigned char *p = str;
    unsigned int   r = 0;

    while (p && *p ) {
        r <<= 1;
        r += (unsigned int)((*p++) & 0x01);
    }

    return (int) r;
}

void main(int argc, char **argv ){
	yyin = fopen(argv[1], "r" );

    yylex();
    return;
}
