
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 93
#define YY_END_OF_BUFFER 94
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[278] =
    {   0,
        0,    0,   75,   75,    0,    0,   94,   93,   45,   39,
       53,   72,   26,   93,   46,   47,   24,   22,   43,   23,
       42,   25,   76,   76,   44,   31,   36,   30,   52,   92,
       50,   51,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   48,   93,
       49,   36,   75,   75,   55,   71,   56,   93,   56,   29,
       72,   37,   27,   40,   87,    0,    0,   80,    0,    0,
        0,    0,    0,    0,    0,   76,   76,   88,   77,   33,
       28,   32,    0,   90,   92,    0,   89,   89,   89,   89,
       89,   89,    6,   89,   89,   89,   89,    7,   13,   89,

       15,   89,   89,   89,   89,   89,   89,   38,    0,   75,
       75,   55,   54,   67,   68,   66,   58,   59,   64,   62,
       57,   63,   65,   60,   61,   70,   41,   87,   87,   87,
       86,   80,   81,   84,    0,   78,    0,    0,   86,    0,
       82,    0,   81,    0,    0,    0,    0,    0,   86,   88,
        0,    0,   77,   88,   88,   86,    0,   76,   77,   34,
       35,   91,   90,    0,    1,   89,   89,    4,   89,   10,
       89,   12,   14,   89,   89,   89,   89,   89,   89,    0,
       75,   68,   70,   69,    0,   87,    0,   80,   81,   84,
       85,   85,   78,   79,   79,   86,    0,   82,   83,   83,

       81,    0,    0,    0,   86,   86,   87,   88,   87,   86,
       77,   88,   86,   86,   88,   77,   91,    0,   89,   89,
       89,    8,   89,   89,   89,   17,   18,   19,   89,   89,
        0,   74,   68,   69,    0,   87,   86,   84,   85,   85,
       78,   79,   79,   86,   82,   83,   83,    0,   86,   87,
       88,   88,   87,   87,    0,   86,   86,    2,    3,   89,
        9,   11,   89,   20,   21,    0,    0,   87,   87,   86,
       89,   16,   73,   87,   89,    5,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   19,   19,    1,   20,   21,
       22,   23,   24,   25,   26,   27,   26,   28,   29,   26,
       30,   30,   30,   30,   30,   30,   30,   30,   31,   30,
       30,   30,   30,   30,   30,   30,   30,   32,   30,   30,
       33,   34,   35,    1,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   46,   46,   47,   46,   48,
       49,   46,   46,   50,   51,   52,   53,   54,   55,   56,
       46,   46,   57,   58,   59,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[60] =
    {   0,
        1,    2,    1,    3,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    1,    6,    6,    6,    6,    1,
        1,    1,    1,    1,    7,    6,    6,    6,    6,    8,
        8,    8,    1,    4,    1,    9,   10,   10,   10,   10,
       10,   10,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,    4,    1,    4
    } ;

static const flex_int16_t yy_base[296] =
    {   0,
        0,  684,  703,   58,   59,   63,  703, 1226, 1226,  680,
     1226,    0, 1226,  687, 1226, 1226,  683, 1226, 1226, 1226,
       55, 1226,  109,   65, 1226,  670,  669,  667,  663,    0,
     1226, 1226,   52,   48,   61,   56,   63,   62,   84,  665,
       71,   75,   64,   76,   91,   85,   86,  116, 1226,  620,
     1226,   70,    0,  636,    0, 1226,  618,  162, 1226, 1226,
        0, 1226, 1226,  660,  137,  145,  151,  158,  155,  165,
      204,  169,  629,  208,  213,  242,  251,  282,  288,  641,
      641, 1226,    0,    0,    0,  258,  637,  175,  117,   72,
      183,   97,  636,   93,  179,   81,  138,  635,  624,  176,

      623,  181,  145,  193,  184,  195,  132, 1226,  595,    0,
      587,    0, 1226, 1226,  234, 1226, 1226, 1226, 1226, 1226,
     1226, 1226, 1226, 1226, 1226,  314,  611,  272,  330,  343,
      309,  298,  303,  246,  347,  351,  354,  318,  358,  364,
      588,  586,  368,  372,  374,  379,  585,  395,  403,  409,
      435,  441,  449,  470,  477,  483,  491,  512,  520, 1226,
     1226,    0,    0,  606,  604,  239,  192,  252,  388,  597,
      194,  594,  593,  188,  267,  265,  271,  385,  351,  563,
      542,  389,  546,    0,  541,  456,  424,  499,  534,  445,
      487,  530,  562,  573,  577,  583,  526,  533,  532,  518,

      587,  598,  612,  626,  640,  654,  668,  682,  696,  710,
      724,  738,  752,  766,  780,  794,    0,  519,  387,  259,
      389,  508,  404,  442,  308,  507,  504,  500,  433,  484,
      466,    0, 1226, 1226,  801,  808,  822,  616,  630,  644,
      829,  836,  843,  850,  412,  398,  380,  859,  873,  887,
      901,  915,  929,  943,  957,  971,  985,  364,  289,  526,
      241,  224,  562,  134,  129,   94,  999, 1013, 1027, 1041,
      557,   73, 1226, 1055,  455, 1226, 1226, 1096, 1107, 1118,
     1123, 1129, 1136, 1147, 1158, 1164, 1166, 1172, 1183, 1189,
     1194, 1199, 1205, 1210, 1215

    } ;

static const flex_int16_t yy_def[296] =
    {   0,
      277,    1,  278,  278,  279,  279,  277,  277,  277,  277,
      277,  280,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  281,  282,
      277,  277,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  277,  277,
      277,  277,  284,  284,  285,  277,  277,  277,  277,  277,
      280,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  286,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  287,  288,  282,  277,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,

      283,  283,  283,  283,  283,  283,  283,  277,  277,  284,
      284,  285,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  289,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      290,  291,  277,  277,  277,  277,  291,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  292,  288,  277,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  277,
      284,  277,  289,  293,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  290,  294,  295,

      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  292,  277,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      277,  284,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  294,  295,  295,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  283,  283,  283,
      283,  283,  283,  283,  283,  277,  277,  277,  277,  277,
      283,  283,  277,  277,  283,  277,    0,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277

    } ;

static const flex_int16_t yy_nxt[1286] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   24,   24,   25,
       26,   27,   28,    8,   29,   30,   30,   30,   30,   30,
       30,   30,   31,    8,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   40,   41,   40,   40,   42,   43,   44,
       45,   46,   47,   40,   48,   40,   49,   50,   51,    8,
        8,  277,   56,   57,    8,   86,   56,   57,   64,  277,
       65,   65,   65,   65,  277,  277,  277,  277,   75,   54,
       76,   77,   77,   77,  277,  277,  277,   88,  277,  277,
       66,   81,   58,   78,  277,   89,   58,  277,  277,  277,

       79,   90,   91,   92,  277,   78,  277,  109,   94,   95,
      277,   93,   98,  101,  166,   59,  102,   59,   99,   59,
       96,   59,   67,  100,   68,   68,   68,  171,  104,  277,
      277,  103,   97,  106,  105,   69,   70,   71,  168,   72,
       73,  273,  277,  169,   74,  277,   69,  277,   70,   71,
       86,  277,  128,  129,  129,  129,  165,   72,  277,  107,
       65,   65,   65,   65,   73,  114,  131,  131,  131,  131,
      134,  134,  130,  132,  132,  132,  179,  115,  115,  115,
       66,  136,  136,  136,   68,   68,   68,  172,   86,  277,
      135,  175,  277,  133,  277,  116,  277,  277,  117,  118,

      137,  277,  119,  120,  140,  277,  277,  277,  277,  121,
       88,  122,  123,  124,  138,  125,  138,  126,  170,  167,
      139,  139,  139,  143,  143,  143,  148,  173,  149,  149,
      149,  149,  174,  176,  144,  145,  177,  277,  146,  147,
      225,  150,  220,   74,  224,  144,  178,  145,  151,  182,
      182,  182,  277,  150,  277,  152,  146,   76,   76,   76,
       76,  190,  190,  147,   75,  277,   76,   77,   77,   77,
       78,  164,  277,   65,   65,   65,   65,  153,  277,   78,
      277,  191,   78,  219,  277,   86,   79,  128,  129,  129,
      129,   78,  138,   66,  138,  154,  221,  155,  156,  156,

      156,  157,  277,  158,  158,  158,  158,  130,  226,  259,
      150,  228,  227,  132,  132,  132,  150,  154,  188,  188,
      188,  277,  150,  159,  131,  131,  131,  131,  150,  184,
      184,  184,  184,  133,  139,  139,  139,   71,  189,  184,
      184,  184,  184,   86,  187,  128,  129,  129,  129,   71,
      184,  184,  184,  184,  184,  184,   86,  263,  186,  186,
      186,  186,  192,  192,  277,  130,  193,  193,  193,  193,
      195,  195,  195,  196,  196,  196,  196,  277,  130,  143,
      143,  143,  135,  201,  201,  201,  194,  192,  192,  137,
      195,  195,  195,  197,  143,  143,  143,  230,  277,  140,

      277,  277,  277,  189,  233,  233,  233,  135,  202,  137,
      203,  203,  203,  203,  140,  246,  157,  277,  205,  206,
      206,  206,  154,  150,  155,  208,  208,  208,  222,  229,
      204,   78,  223,  246,  258,  150,  260,  150,  207,  237,
      237,  237,  237,   78,  154,  261,  277,  199,  204,  150,
      209,  209,  209,  209,  204,  277,  210,  210,  210,  210,
      190,  190,  204,  150,  158,  158,  158,  158,  277,  150,
      151,  186,  186,  186,  186,  150,  204,  150,  276,  264,
      191,  150,  262,  154,  211,  155,  208,  208,  208,  150,
      154,  236,  155,  208,  208,  208,  212,  277,  213,  214,

      214,  214,  238,  238,  148,  154,  209,  209,  209,  209,
      266,  150,  154,  277,  188,  188,  188,  277,  215,  150,
      277,  277,  239,  150,  265,  152,  151,  158,  158,  158,
      158,  150,  185,  157,  133,  216,  216,  216,  216,  277,
       78,  244,  244,  244,  244,  240,  240,  153,  150,  201,
      201,  201,   78,  246,  235,  159,   65,   65,   65,   65,
      150,  277,  277,  277,  277,  239,  271,  246,  199,  189,
      277,  277,  277,  277,  277,  277,   66,  193,  193,  193,
      193,  232,  277,  277,  277,  277,  277,  277,  241,  241,
      241,  241,  243,  243,  243,  243,  275,  194,  196,  196,

      196,  196,  201,  201,  201,  231,  277,  277,  242,  272,
      277,  248,  242,  203,  203,  203,  203,  277,  197,  218,
      142,  142,  189,  199,  185,  204,  150,  203,  203,  203,
      203,  238,  238,  204,  181,  180,  277,  277,  150,  204,
      150,  203,  203,  203,  203,  240,  240,  204,  277,  277,
      277,  191,  150,  157,  150,  205,  206,  206,  206,  240,
      240,  204,  161,  160,  142,  239,  150,  157,   78,  205,
      206,  206,  206,  127,  113,  207,  111,  108,  277,  239,
       78,  157,   78,  249,  249,  249,  249,   83,   82,  207,
       81,   80,   63,   62,   78,  212,  150,  251,  252,  252,

      252,   60,  277,  250,    8,   52,  277,  277,  150,  157,
      150,  253,  254,  254,  254,  277,  277,  212,  277,  277,
      277,  277,  150,  204,  150,  210,  210,  210,  210,  277,
      277,  250,  277,  277,  277,  277,  150,  204,   78,  216,
      216,  216,  216,  277,  277,  255,  277,  277,  277,  277,
       78,  212,  150,  251,  252,  252,  252,  277,  277,  211,
      277,  277,  277,  277,  150,  212,  150,  213,  214,  214,
      214,  277,  277,  212,  277,  277,  277,  277,  150,  212,
      150,  213,  214,  214,  214,  277,  277,  215,  277,  277,
      277,  277,  150,  212,  150,  256,  257,  257,  257,  277,

      277,  215,  277,  277,  277,  277,  150,  204,  150,  216,
      216,  216,  216,  277,  235,  212,   65,   65,   65,   65,
      150,  277,  150,  186,  186,  186,  186,  277,  277,  211,
      277,  277,  277,  277,  150,  277,   66,  237,  237,  237,
      237,  277,  277,  236,  241,  241,  241,  241,  277,  277,
       71,  243,  243,  243,  243,  277,  277,  187,  243,  243,
      243,  243,   71,  277,  194,  244,  244,  244,  244,  277,
      277,  242,  267,  277,  209,  209,  209,  209,  242,  277,
      277,  277,  277,  277,  277,  197,  204,  150,  249,  249,
      249,  249,  277,  277,  151,  277,  277,  277,  277,  150,

      157,   78,  269,  269,  269,  269,  277,  277,  268,  277,
      277,  277,  277,   78,  212,  150,  251,  252,  252,  252,
      277,  277,  250,  277,  277,  277,  277,  150,  212,  150,
      251,  252,  252,  252,  277,  277,  212,  277,  277,  277,
      277,  150,  157,  150,  253,  254,  254,  254,  277,  277,
      212,  277,  277,  277,  277,  150,  157,  150,  253,  254,
      254,  254,  277,  277,  250,  277,  277,  277,  277,  150,
      204,  150,  270,  270,  270,  270,  277,  277,  250,  277,
      277,  277,  277,  150,  212,  150,  256,  257,  257,  257,
      277,  277,  204,  277,  277,  277,  277,  150,  212,  150,

      256,  257,  257,  257,  277,  277,  215,  277,  277,  277,
      277,  150,  267,  150,  209,  209,  209,  209,  277,  277,
      215,  277,  277,  277,  277,  150,  204,  150,  249,  249,
      249,  249,  277,  277,  151,  277,  277,  277,  277,  150,
      204,  150,  269,  269,  269,  269,  277,  277,  274,  277,
      277,  277,  277,  150,  204,  150,  270,  270,  270,  270,
      277,  277,  274,  277,  277,  277,  277,  150,  204,   78,
      269,  269,  269,  269,  277,  277,  255,  277,  277,  277,
      277,   78,  277,  150,  277,  277,  277,  277,  277,  277,
      274,  277,  277,  277,  277,  150,   53,   53,   53,   53,

       53,   53,   53,   53,   53,   53,   53,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   61,  277,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   84,
      277,   84,   84,   84,   85,  277,   85,   85,   85,   85,
       87,   87,  277,   87,   87,   87,   87,  110,  277,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  112,  277,
      277,  277,  112,  112,  112,  112,  112,  112,  112,  141,
      277,  277,  141,  141,  162,  162,  162,  163,  277,  163,
      163,  163,  163,  183,  277,  277,  183,  183,  183,  183,
      183,  183,  183,  183,  198,  277,  277,  198,  198,  200,

      277,  277,  200,  200,  217,  277,  217,  217,  217,  217,
      234,  277,  277,  277,  234,  245,  277,  277,  245,  245,
      247,  277,  277,  247,  247,    7,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277
    } ;

static const flex_int16_t yy_chk[1286] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        5,   34,    5,    5,    6,   33,    6,    6,   21,   36,
       21,   21,   21,   21,   35,   38,   37,   43,   24,    4,
       24,   24,   24,   24,   41,   90,  272,   33,   42,   44,
       21,   52,    5,   24,   96,   34,    6,   39,   46,   47,

       24,   35,   36,   37,   45,   24,   94,   52,   38,   38,
       92,   37,   41,   43,   90,    5,   44,    5,   41,    6,
       39,    6,   23,   42,   23,   23,   23,   96,   46,   48,
       89,   45,   39,   47,   46,   23,   23,   23,   92,   23,
       23,  266,  265,   94,   23,  107,   23,  264,   23,   23,
       65,   97,   65,   65,   65,   65,   89,   23,  103,   48,
       66,   66,   66,   66,   23,   58,   67,   67,   67,   67,
       69,   69,   65,   68,   68,   68,  107,   58,   58,   58,
       66,   70,   70,   70,   72,   72,   72,   97,   88,  100,
       69,  103,   95,   68,  102,   58,   91,  105,   58,   58,

       70,  174,   58,   58,   72,  167,  104,  171,  106,   58,
       88,   58,   58,   58,   71,   58,   71,   58,   95,   91,
       71,   71,   71,   74,   74,   74,   75,  100,   75,   75,
       75,   75,  102,  104,   74,   74,  105,  262,   74,   74,
      174,   75,  167,   74,  171,   74,  106,   74,   75,  115,
      115,  115,  166,   75,  261,   76,   74,   76,   76,   76,
       76,  134,  134,   74,   77,  168,   77,   77,   77,   77,
       76,   86,  220,   86,   86,   86,   86,   76,  176,   77,
      175,  134,   76,  166,  177,  128,   77,  128,  128,  128,
      128,   77,   78,   86,   78,   78,  168,   78,   78,   78,

       78,   79,  259,   79,   79,   79,   79,  128,  175,  220,
       78,  177,  176,  132,  132,  132,   79,   78,  133,  133,
      133,  225,   78,   79,  131,  131,  131,  131,   79,  126,
      126,  126,  126,  132,  138,  138,  138,  131,  133,  126,
      126,  126,  126,  129,  131,  129,  129,  129,  129,  131,
      126,  126,  126,  126,  126,  126,  130,  225,  130,  130,
      130,  130,  135,  135,  179,  129,  136,  136,  136,  136,
      137,  137,  137,  139,  139,  139,  139,  258,  130,  140,
      140,  140,  135,  143,  143,  143,  136,  144,  144,  137,
      145,  145,  145,  139,  146,  146,  146,  179,  178,  140,

      219,  169,  221,  143,  182,  182,  182,  144,  148,  145,
      148,  148,  148,  148,  146,  247,  149,  223,  149,  149,
      149,  149,  150,  148,  150,  150,  150,  150,  169,  178,
      148,  149,  169,  246,  219,  148,  221,  150,  149,  187,
      187,  187,  187,  149,  150,  223,  229,  245,  151,  150,
      151,  151,  151,  151,  152,  224,  152,  152,  152,  152,
      190,  190,  153,  151,  153,  153,  153,  153,  275,  152,
      151,  186,  186,  186,  186,  151,  152,  153,  275,  229,
      190,  152,  224,  154,  153,  154,  154,  154,  154,  153,
      155,  186,  155,  155,  155,  155,  156,  230,  156,  156,

      156,  156,  191,  191,  157,  154,  157,  157,  157,  157,
      231,  156,  155,  228,  188,  188,  188,  227,  156,  157,
      226,  222,  191,  156,  230,  158,  157,  158,  158,  158,
      158,  157,  218,  159,  188,  159,  159,  159,  159,  260,
      158,  197,  197,  197,  197,  192,  192,  158,  159,  189,
      189,  189,  158,  200,  185,  159,  185,  185,  185,  185,
      159,  183,  183,  183,  183,  192,  260,  199,  198,  189,
      271,  183,  183,  183,  183,  263,  185,  193,  193,  193,
      193,  181,  183,  183,  183,  183,  183,  183,  194,  194,
      194,  194,  195,  195,  195,  195,  271,  193,  196,  196,

      196,  196,  201,  201,  201,  180,  173,  172,  194,  263,
      170,  202,  195,  202,  202,  202,  202,  165,  196,  164,
      147,  142,  201,  141,  127,  203,  202,  203,  203,  203,
      203,  238,  238,  202,  111,  109,  101,   99,  202,  204,
      203,  204,  204,  204,  204,  239,  239,  203,   98,   93,
       87,  238,  203,  205,  204,  205,  205,  205,  205,  240,
      240,  204,   81,   80,   73,  239,  204,  206,  205,  206,
      206,  206,  206,   64,   57,  205,   54,   50,   40,  240,
      205,  207,  206,  207,  207,  207,  207,   29,   28,  206,
       27,   26,   17,   14,  206,  208,  207,  208,  208,  208,

      208,   10,    7,  207,    3,    2,    0,    0,  207,  209,
      208,  209,  209,  209,  209,    0,    0,  208,    0,    0,
        0,    0,  208,  210,  209,  210,  210,  210,  210,    0,
        0,  209,    0,    0,    0,    0,  209,  211,  210,  211,
      211,  211,  211,    0,    0,  210,    0,    0,    0,    0,
      210,  212,  211,  212,  212,  212,  212,    0,    0,  211,
        0,    0,    0,    0,  211,  213,  212,  213,  213,  213,
      213,    0,    0,  212,    0,    0,    0,    0,  212,  214,
      213,  214,  214,  214,  214,    0,    0,  213,    0,    0,
        0,    0,  213,  215,  214,  215,  215,  215,  215,    0,

        0,  214,    0,    0,    0,    0,  214,  216,  215,  216,
      216,  216,  216,    0,  235,  215,  235,  235,  235,  235,
      215,    0,  216,  236,  236,  236,  236,    0,    0,  216,
        0,    0,    0,    0,  216,    0,  235,  237,  237,  237,
      237,    0,    0,  236,  241,  241,  241,  241,    0,    0,
      237,  242,  242,  242,  242,    0,    0,  237,  243,  243,
      243,  243,  237,    0,  241,  244,  244,  244,  244,    0,
        0,  242,  248,    0,  248,  248,  248,  248,  243,    0,
        0,    0,    0,    0,    0,  244,  249,  248,  249,  249,
      249,  249,    0,    0,  248,    0,    0,    0,    0,  248,

      250,  249,  250,  250,  250,  250,    0,    0,  249,    0,
        0,    0,    0,  249,  251,  250,  251,  251,  251,  251,
        0,    0,  250,    0,    0,    0,    0,  250,  252,  251,
      252,  252,  252,  252,    0,    0,  251,    0,    0,    0,
        0,  251,  253,  252,  253,  253,  253,  253,    0,    0,
      252,    0,    0,    0,    0,  252,  254,  253,  254,  254,
      254,  254,    0,    0,  253,    0,    0,    0,    0,  253,
      255,  254,  255,  255,  255,  255,    0,    0,  254,    0,
        0,    0,    0,  254,  256,  255,  256,  256,  256,  256,
        0,    0,  255,    0,    0,    0,    0,  255,  257,  256,

      257,  257,  257,  257,    0,    0,  256,    0,    0,    0,
        0,  256,  267,  257,  267,  267,  267,  267,    0,    0,
      257,    0,    0,    0,    0,  257,  268,  267,  268,  268,
      268,  268,    0,    0,  267,    0,    0,    0,    0,  267,
      269,  268,  269,  269,  269,  269,    0,    0,  268,    0,
        0,    0,    0,  268,  270,  269,  270,  270,  270,  270,
        0,    0,  269,    0,    0,    0,    0,  269,  274,  270,
      274,  274,  274,  274,    0,    0,  270,    0,    0,    0,
        0,  270,    0,  274,    0,    0,    0,    0,    0,    0,
      274,    0,    0,    0,    0,  274,  278,  278,  278,  278,

      278,  278,  278,  278,  278,  278,  278,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  280,    0,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  281,
        0,  281,  281,  281,  282,    0,  282,  282,  282,  282,
      283,  283,    0,  283,  283,  283,  283,  284,    0,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  285,    0,
        0,    0,  285,  285,  285,  285,  285,  285,  285,  286,
        0,    0,  286,  286,  287,  287,  287,  288,    0,  288,
      288,  288,  288,  289,    0,    0,  289,  289,  289,  289,
      289,  289,  289,  289,  290,    0,    0,  290,  290,  291,

        0,    0,  291,  291,  292,    0,  292,  292,  292,  292,
      293,    0,    0,    0,  293,  294,    0,    0,  294,  294,
      295,    0,    0,  295,  295,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[94] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "RubyLexer.l"
#line 6 "RubyLexer.l"
	#include <stdio.h>    
    #include "parser.tab.h" 
    #include "tree_nodes.h"   

    void removeCharacterFromString(const char * str, char * dest, char deleted_char);
    int binstrToDec(const char * str);
#line 856 "lex.yy.c"

#line 858 "lex.yy.c"

#define INITIAL 0
#define ML_COMMENT 1
#define STRING 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 29 "RubyLexer.l"


   
#line 33 "RubyLexer.l"
    int num;
    float real_num;
    char temp1[100];
    char temp2[100];
    char comment[1000];
    char string[1000];
    int concatenation = 0;


#line 1094 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 278 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 277 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 42 "RubyLexer.l"
{ return AND; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 43 "RubyLexer.l"
{ return BEGIN_KEYWORD; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 44 "RubyLexer.l"
{ return CLASS; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 45 "RubyLexer.l"
{ return DEF; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "RubyLexer.l"
{ return DEFINED; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 47 "RubyLexer.l"
{ return DO; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 48 "RubyLexer.l"
{ return IF; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 49 "RubyLexer.l"
{ return ELSE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 50 "RubyLexer.l"
{ return ELSIF; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 51 "RubyLexer.l"
{ return END; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 52 "RubyLexer.l"
{ return FALSE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 53 "RubyLexer.l"
{ return FOR; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 54 "RubyLexer.l"
{ return IN; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 55 "RubyLexer.l"
{ return NOT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 56 "RubyLexer.l"
{ return OR; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 57 "RubyLexer.l"
{ return RETURN; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 58 "RubyLexer.l"
{ return SELF; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 59 "RubyLexer.l"
{ return THEN; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 60 "RubyLexer.l"
{ return TRUE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 61 "RubyLexer.l"
{ return UNTIL; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 62 "RubyLexer.l"
{ return WHILE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 64 "RubyLexer.l"
{ return ARITHMETIC_PLUS_OP; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 65 "RubyLexer.l"
{ return ARITHMETIC_MINUS_OP; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 66 "RubyLexer.l"
{ return ARITHMETIC_MUL_OP; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 67 "RubyLexer.l"
{ return ARITHMETIC_DIV_OP; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 68 "RubyLexer.l"
{ return ARITHMETIC_MOD_OP; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 69 "RubyLexer.l"
{ return ARITHMETIC_POW_OP; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 71 "RubyLexer.l"
{ return EQL_OP; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 72 "RubyLexer.l"
{ return NOT_EQL_OP; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 73 "RubyLexer.l"
{ return GREATER_OP; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 74 "RubyLexer.l"
{ return LESS_OP; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 75 "RubyLexer.l"
{ return GREATER_OR_EQL_OP; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 76 "RubyLexer.l"
{ return LESS_OR_EQL_OP; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 77 "RubyLexer.l"
{ return COMB_COMPRASION_OP; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 78 "RubyLexer.l"
{ return CASE_EQL_OP; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 80 "RubyLexer.l"
{ return ASSIGN_OP; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 82 "RubyLexer.l"
{ return LOGICAL_AND_OP; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 83 "RubyLexer.l"
{ return LOGICAL_OR_OP; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 84 "RubyLexer.l"
{ return LOGICAL_NOT_OP; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 86 "RubyLexer.l"
{ return INCLUSIVE_RANGE_OP; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 87 "RubyLexer.l"
{ return EXCLUSIVE_RANGE_OP; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 89 "RubyLexer.l"
{ return DOT_SYMBOL; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 90 "RubyLexer.l"
{ return COMMA_SYMBOL; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 91 "RubyLexer.l"
{ return SEMICOLON_SYMBOL; }
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 92 "RubyLexer.l"
{ return NEW_LINE_SYMBOL;  }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 93 "RubyLexer.l"
{ return OPEN_ROUND_BRACKET; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 94 "RubyLexer.l"
{ return CLOSE_ROUND_BRACKET; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 95 "RubyLexer.l"
{ return OPEN_CURLY_BRACKET; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 96 "RubyLexer.l"
{
                if(concatenation == 0) {
                    return CLOSE_CURLY_BRACKET;
                } else {
                    concatenation--;
                    BEGIN(STRING);
                    string[0] = 0;
                    return ARITHMETIC_PLUS_OP;
                }
            }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 106 "RubyLexer.l"
{ return OPEN_SQUARE_BRACKET; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 107 "RubyLexer.l"
{ return CLOSE_SQUARE_BRACKET; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 108 "RubyLexer.l"
{ return COMMERCIAL_AT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 110 "RubyLexer.l"
{ 
                string[0] = 0; 
                BEGIN(STRING);    
            }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 115 "RubyLexer.l"
{                         
                        concatenation++;
                        BEGIN(INITIAL);
                    }            
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 120 "RubyLexer.l"
{ strcat(string, yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 121 "RubyLexer.l"
{ strcat(string, yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 122 "RubyLexer.l"
{ strcat(string, "\n"); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 123 "RubyLexer.l"
{ strcat(string, "\a"); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 124 "RubyLexer.l"
{ strcat(string, "\b"); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 125 "RubyLexer.l"
{ strcat(string, "\t"); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 126 "RubyLexer.l"
{ strcat(string, "\v"); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 127 "RubyLexer.l"
{ strcat(string, "\f"); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 128 "RubyLexer.l"
{ strcat(string, "\r"); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 129 "RubyLexer.l"
{ strcat(string, "\e"); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 130 "RubyLexer.l"
{ strcat(string, " "); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 131 "RubyLexer.l"
{ strcat(string, "\\"); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 132 "RubyLexer.l"
{ strcat(string, "\""); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 133 "RubyLexer.l"
{ 
                                sscanf(yytext + 1, "%o", &num);
                                temp1[0] = (char) num;
                                temp1[1] = 0;
                                strcat(string, temp1);
                            }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 140 "RubyLexer.l"
{ 
                                sscanf(yytext + 2, "%x", &num);
                                temp1[0] = (char) num;
                                temp1[1] = 0;
                                strcat(string, temp1);
                            }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 146 "RubyLexer.l"
{ printf("ERROR: invalid hex escape \n"); } 
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 147 "RubyLexer.l"
{ printf("ERROR: expected \" \n");}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 148 "RubyLexer.l"
{ 
                yylval.string_un=(char *)malloc(strlen(string)+1);
                strcpy(yylval.string_un, string);
                BEGIN(INITIAL);
                return STRING;
            }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 155 "RubyLexer.l"
{ printf("Single-line comment: %s\n", yytext + 1); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 157 "RubyLexer.l"
{                                     
                            comment[0] = 0; 
                            BEGIN(ML_COMMENT);
                        }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 162 "RubyLexer.l"
{
                            strcat(comment, yytext + 5);
                            printf("Multi-line comment: %s\n", comment);
                            BEGIN(INITIAL);
                        }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 168 "RubyLexer.l"
{ 
                            strcat(comment, yytext); 
                        }
	YY_BREAK
case YY_STATE_EOF(ML_COMMENT):
#line 172 "RubyLexer.l"
{ 
                            printf("expected =end"); BEGIN(INITIAL); 
                        }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 176 "RubyLexer.l"
{ 
                                removeCharacterFromString(yytext,temp1,'_');
                                yylval.int_un = atoi(temp1);
                                return INTEGER_NUMBER;
                            }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 182 "RubyLexer.l"
{ printf("ERROR: invalid decimal number: %s\n", yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 184 "RubyLexer.l"
{
                                removeCharacterFromString(yytext+2,temp1,'_');
                                yylval.int_un = atoi(temp1);
                                return INTEGER_NUMBER;              
                            }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 190 "RubyLexer.l"
{ printf("ERROR: invalid decimal number with dD: %s\n", yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 192 "RubyLexer.l"
{
                                removeCharacterFromString(yytext,temp1,'_');
                                removeCharacterFromString(temp1,temp2,'o');
                                removeCharacterFromString(temp2,temp1,'O');
                                yylval.int_un = num;
                                return INTEGER_NUMBER;
                            }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 200 "RubyLexer.l"
{ printf("ERROR: invalid octal number: %s\n", yytext); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 202 "RubyLexer.l"
{
                                removeCharacterFromString(yytext + 2,temp1,'_');
                                yylval.int_un = num;
                                return INTEGER_NUMBER;
                            }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 208 "RubyLexer.l"
{ printf("ERROR: invalid hexadecimal number: %s\n", yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 210 "RubyLexer.l"
{
                                removeCharacterFromString(yytext + 2,temp1,'_');
                                yylval.int_un = num;
                                return INTEGER_NUMBER; 
                            }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 216 "RubyLexer.l"
{ printf("ERROR: invalid binary number: %s\n", yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 219 "RubyLexer.l"
{
                                                                removeCharacterFromString(yytext,temp1,'_');                                                                  
                                                                real_num = (float) atof(temp1);
                                                                yylval.float_un = (float) real_num;
                                                                return FLOAT_NUMBER;
                                                            }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 225 "RubyLexer.l"
{ printf("ERROR: invalid float number: %s\n", yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 226 "RubyLexer.l"
{ printf("ERROR: invalid float number with eE: %s\n", yytext); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 228 "RubyLexer.l"
{
                                                yylval.string_un=(char *)malloc(strlen(yytext)+1);
                                                strcpy(yylval.string_un, yytext); 
                                                return VAR_OR_METHOD_NAME;
                                            }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 234 "RubyLexer.l"
{
                                                yylval.string_un=(char *)malloc(strlen(yytext)+1);
                                                strcpy(yylval.string_un, yytext); 
                                                return INSTANCE_VAR_NAME;
                                            }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 240 "RubyLexer.l"
{
                                                yylval.string_un=(char *)malloc(strlen(yytext)+1);
                                                strcpy(yylval.string_un, yytext); 
                                                return CLASS_VAR_NAME;
                                            }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 246 "RubyLexer.l"
{
                                                yylval.string_un=(char *)malloc(strlen(yytext)+1);
                                                strcpy(yylval.string_un, yytext); 
                                                return CLASS_NAME;
                                            }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 252 "RubyLexer.l"
ECHO;
	YY_BREAK
#line 1716 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 278 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 278 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 277);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 252 "RubyLexer.l"


void removeCharacterFromString(const char * str, char * dest, char deleted_char) {
	int j = 0;
	
    for(int i = 0; str[i] != 0; i++) {
        if(str[i] != deleted_char) {
            dest[j++] = str[i];
        }
    }

    dest[j] = 0;
}

int binstrToDec(const char * str) {
    unsigned char *p = str;
    unsigned int   r = 0;

    while (p && *p ) {
        r <<= 1;
        r += (unsigned int)((*p++) & 0x01);
    }

    return (int) r;
}
